"""Backward-compatibility re-export of the ESM diagnostic-code constants.

The canonical, single source of truth for every diagnostic code -- including
the template / coupling / metaparameter / geometry / closed-function ``str``
constants re-exported here -- is :mod:`earthsci_ast.error_handling` (see its
module docstring for the full registry, the reason the ``ErrorCode`` enum and
these ``str`` constants coexist, and the cross-binding-contract invariant).

This module exists only so the historical import path
``from earthsci_ast.diagnostics import <CODE>`` keeps resolving for its
consumers (``lower_expression_templates``, ``coupling_imports``,
``registered_functions``, ``template_imports``, ``parse``). The VALUES are
CROSS-BINDING CONTRACT STRINGS and must never change; add or edit codes in
:mod:`earthsci_ast.error_handling`, not here.

No import cycle: ``error_handling`` imports only the standard library, so
re-exporting from it here is safe even though ``parse`` and the template
machinery import this module.
"""

from __future__ import annotations

from .error_handling import (
    APPLY_EXPRESSION_TEMPLATE_BINDINGS_MISMATCH,
    APPLY_EXPRESSION_TEMPLATE_INVALID_DECLARATION,
    APPLY_EXPRESSION_TEMPLATE_RECURSIVE_BODY,
    APPLY_EXPRESSION_TEMPLATE_UNKNOWN_TEMPLATE,
    APPLY_EXPRESSION_TEMPLATE_VERSION_TOO_OLD,
    CLOSED_FUNCTION_ARITY,
    CLOSED_FUNCTION_OVERFLOW,
    COUPLING_EDGE_UNKNOWN_ROLE,
    COUPLING_IMPORT_BIND_NOT_A_COMPONENT,
    COUPLING_IMPORT_NOT_LIBRARY,
    COUPLING_IMPORT_ROLE_UNBOUND,
    COUPLING_IMPORT_UNKNOWN_ROLE,
    COUPLING_IMPORT_UNRESOLVED,
    COUPLING_LIBRARY_ILLEGAL_PAYLOAD,
    COUPLING_LIBRARY_NESTED_IMPORT,
    COUPLING_ROLE_UNUSED,
    GEOMETRY_MANIFOLD_INVALID,
    INTERP_AXIS_LENGTH_MISMATCH,
    INTERP_AXIS_TOO_SHORT,
    INTERP_NAN_IN_AXIS,
    INTERP_NON_MONOTONIC_AXIS,
    MAKEARRAY_REGION_INVERTED,
    METAPARAMETER_NAME_CONFLICT,
    METAPARAMETER_TYPE_ERROR,
    METAPARAMETER_UNBOUND,
    REWRITE_RULE_NONTERMINATING,
    SEARCHSORTED_NAN_IN_TABLE,
    SEARCHSORTED_NON_MONOTONIC,
    SUBSYSTEM_REF_IS_COUPLING_LIBRARY,
    SUBSYSTEM_REF_IS_TEMPLATE_LIBRARY,
    TEMPLATE_BODY_EXPANSION_TOO_DEEP,
    TEMPLATE_CONSTRAINT_UNKNOWN_INDEX_SET,
    TEMPLATE_IMPORT_CYCLE,
    TEMPLATE_IMPORT_INDEX_SET_CONFLICT,
    TEMPLATE_IMPORT_IS_COUPLING_LIBRARY,
    TEMPLATE_IMPORT_NAME_CONFLICT,
    TEMPLATE_IMPORT_NOT_LIBRARY,
    TEMPLATE_IMPORT_REBIND_UNKNOWN_NAME,
    TEMPLATE_IMPORT_RENAME_COLLISION,
    TEMPLATE_IMPORT_RENAME_INVALID,
    TEMPLATE_IMPORT_RENAME_UNKNOWN_NAME,
    TEMPLATE_IMPORT_UNKNOWN_NAME,
    TEMPLATE_IMPORT_UNRESOLVED,
    TEMPLATE_IMPORT_VERSION_TOO_OLD,
    TEMPLATE_INJECT_TARGET_IS_LOADER,
    TEMPLATE_INJECT_TARGET_NOT_COMPONENT,
    TEMPLATE_INJECT_TARGET_UNKNOWN,
    UNKNOWN_CLOSED_FUNCTION,
    UNKNOWN_ENUM,
    UNKNOWN_ENUM_SYMBOL,
)

__all__ = [
    # Expression-template codes (esm-spec §9.6 / §9.6.6).
    "APPLY_EXPRESSION_TEMPLATE_INVALID_DECLARATION",
    "APPLY_EXPRESSION_TEMPLATE_UNKNOWN_TEMPLATE",
    "APPLY_EXPRESSION_TEMPLATE_BINDINGS_MISMATCH",
    "APPLY_EXPRESSION_TEMPLATE_RECURSIVE_BODY",
    "APPLY_EXPRESSION_TEMPLATE_VERSION_TOO_OLD",
    "REWRITE_RULE_NONTERMINATING",
    "TEMPLATE_CONSTRAINT_UNKNOWN_INDEX_SET",
    "GEOMETRY_MANIFOLD_INVALID",
    "MAKEARRAY_REGION_INVERTED",
    # Template-library import / metaparameter codes (esm-spec §9.7).
    "TEMPLATE_IMPORT_VERSION_TOO_OLD",
    "TEMPLATE_IMPORT_UNRESOLVED",
    "TEMPLATE_IMPORT_NOT_LIBRARY",
    "SUBSYSTEM_REF_IS_TEMPLATE_LIBRARY",
    "TEMPLATE_IMPORT_CYCLE",
    "TEMPLATE_IMPORT_NAME_CONFLICT",
    "TEMPLATE_IMPORT_UNKNOWN_NAME",
    "TEMPLATE_IMPORT_INDEX_SET_CONFLICT",
    "TEMPLATE_BODY_EXPANSION_TOO_DEEP",
    "METAPARAMETER_UNBOUND",
    "METAPARAMETER_TYPE_ERROR",
    "METAPARAMETER_NAME_CONFLICT",
    # Import-renaming codes (esm-spec §9.7.7).
    "TEMPLATE_IMPORT_RENAME_UNKNOWN_NAME",
    "TEMPLATE_IMPORT_REBIND_UNKNOWN_NAME",
    "TEMPLATE_IMPORT_RENAME_COLLISION",
    "TEMPLATE_IMPORT_RENAME_INVALID",
    # Scope-injection codes (esm-spec §9.7.10).
    "TEMPLATE_INJECT_TARGET_UNKNOWN",
    "TEMPLATE_INJECT_TARGET_NOT_COMPONENT",
    "TEMPLATE_INJECT_TARGET_IS_LOADER",
    # Coupling-library / coupling_import role-binding codes (esm-spec §10.9–§10.11).
    "COUPLING_IMPORT_UNRESOLVED",
    "COUPLING_IMPORT_NOT_LIBRARY",
    "SUBSYSTEM_REF_IS_COUPLING_LIBRARY",
    "TEMPLATE_IMPORT_IS_COUPLING_LIBRARY",
    "COUPLING_LIBRARY_ILLEGAL_PAYLOAD",
    "COUPLING_LIBRARY_NESTED_IMPORT",
    "COUPLING_EDGE_UNKNOWN_ROLE",
    "COUPLING_ROLE_UNUSED",
    "COUPLING_IMPORT_UNKNOWN_ROLE",
    "COUPLING_IMPORT_ROLE_UNBOUND",
    "COUPLING_IMPORT_BIND_NOT_A_COMPONENT",
    # Closed function registry codes (esm-spec §9.1–§9.3).
    "UNKNOWN_CLOSED_FUNCTION",
    "CLOSED_FUNCTION_ARITY",
    "CLOSED_FUNCTION_OVERFLOW",
    "SEARCHSORTED_NON_MONOTONIC",
    "SEARCHSORTED_NAN_IN_TABLE",
    "INTERP_NON_MONOTONIC_AXIS",
    "INTERP_AXIS_LENGTH_MISMATCH",
    "INTERP_NAN_IN_AXIS",
    "INTERP_AXIS_TOO_SHORT",
    "UNKNOWN_ENUM",
    "UNKNOWN_ENUM_SYMBOL",
]
