//! A right-hand-side structural `D(x, t)` resolves to `x`'s TENDENCY
//! (issue #206 item 2).
//!
//! `D` on an equation's left-hand side is what makes the equation
//! differential. On a right-hand side there was no consumer, and all three
//! Rust evaluators answered `D(anything) = 0` "for parity" with one another —
//! so an observed written `dxdt ~ D(x, t)`, the standard shape for asserting a
//! species tendency at `t = 0` (esm-spec §6.6.2, "instantaneous-derivative
//! test shape"), read as exactly `0` and its inline test graded a
//! configuration the model never computed.
//!
//! The value was never the runner's to invent: `x` already carries a defining
//! `D(x)/dt ~ f` equation in the same flattened system. `flatten` phase 5b′
//! (`resolve_rhs_time_derivatives`) substitutes it, upstream of every runner,
//! which is also what lets a model's scoped `D(Chem.A, t)` resolve to a
//! sibling reaction system's mass-action tendency (esm-spec §7.4) without
//! either runner learning anything about reactions.
//!
//! Sabotage check: delete the `resolve_rhs_time_derivatives` call from
//! `flatten_impl` and every numeric test here reports `0` instead.

#![cfg(not(target_arch = "wasm32"))]

use earthsci_ast::{AssertionResult, SolveOptions, flatten, load_string, run_inline_tests};
use serde_json::json;

mod common;

fn opts() -> SolveOptions {
    SolveOptions {
        reltol: Some(1e-10),
        abstol: Some(1e-12),
        ..Default::default()
    }
}

fn run(doc: &serde_json::Value) -> Vec<AssertionResult> {
    let file = load_string(&doc.to_string()).expect("document loads");
    run_inline_tests(&file, None, &opts())
}

/// `D(x)/dt = -k·x` with `k = 3`, `x(0) = 2`, plus an observed `dxdt = D(x, t)`
/// asserted at `t = 0`: the tendency is `-6`, and used to read `0`.
fn own_state_doc() -> serde_json::Value {
    json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "DObsOwn",
            "description": "An observed defined as D(x, t) of this model's own ODE state.",
            "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "x": {"type": "unknown", "units": "kg", "default": 2.0},
                    "k": {"type": "parameter", "units": "1/s", "default": 3.0},
                    "dxdt": {"type": "unknown", "units": "kg/s"}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["x"], "wrt": "t"},
                     "rhs": {"op": "*", "args": [{"op": "-", "args": ["k"]}, "x"]}},
                    {"lhs": "dxdt", "rhs": {"op": "D", "args": ["x"], "wrt": "t"}}
                ],
                "tests": [{
                    "id": "tendency_at_zero",
                    "time_span": {"start": 0.0, "end": 1.0},
                    "assertions": [
                        {"variable": "x", "time": 0.0, "expected": 2.0,
                         "tolerance": {"abs": 1e-12}},
                        {"variable": "dxdt", "time": 0.0, "expected": -6.0,
                         "tolerance": {"abs": 1e-9}}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    })
}

#[test]
fn observed_derivative_of_own_state_is_the_tendency() {
    let results = run(&own_state_doc());
    assert_eq!(results.len(), 2, "{results:?}");
    let dxdt = results
        .iter()
        .find(|r| r.variable == "dxdt")
        .expect("dxdt row");
    assert!(
        dxdt.passed,
        "D(x, t) on a right-hand side must be x's tendency, not 0: {dxdt:?}"
    );
    assert_eq!(dxdt.actual, Some(-6.0), "{dxdt:?}");
}

/// The scoped-reference form the issue reports: a wrapper model observes the
/// tendency of a species owned by a sibling REACTION SYSTEM. The mass-action
/// ODE `D(Chem.A)/dt = -k·A` is generated by flatten (esm-spec §7.4), so the
/// substitution resolves against it with no runner-side knowledge of
/// reactions. `k = 0.5`, `A(0) = 4` ⇒ `dAdt(0) = -2`.
#[test]
fn observed_derivative_of_a_sibling_reaction_systems_species() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "RsScoped",
            "description": "A model observing a sibling reaction system's species tendency.",
            "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "reaction_systems": {
            "Chem": {
                "species": {
                    "A": {"units": "mol/mol", "default": 4.0},
                    "B": {"units": "mol/mol", "default": 0.0}
                },
                "parameters": {"k": {"units": "1/s", "default": 0.5}},
                "reactions": [{
                    "id": "R1",
                    "substrates": [{"species": "A", "stoichiometry": 1}],
                    "products": [{"species": "B", "stoichiometry": 1}],
                    "rate": "k"
                }]
            }
        },
        "models": {
            "Probe": {
                "variables": {
                    "dAdt": {"type": "unknown", "units": "mol/mol/s"}
                },
                "equations": [
                    {"lhs": "dAdt", "rhs": {"op": "D", "args": ["Chem.A"], "wrt": "t"}}
                ],
                "tests": [{
                    "id": "scoped_tendency_at_zero",
                    "time_span": {"start": 0.0, "end": 1.0},
                    "assertions": [
                        {"variable": "dAdt", "time": 0.0, "expected": -2.0,
                         "tolerance": {"abs": 1e-9}}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    });
    let results = run(&doc);
    assert_eq!(results.len(), 1, "{results:?}");
    assert!(results[0].passed, "{:?}", results[0]);
    assert_eq!(results[0].actual, Some(-2.0), "{:?}", results[0]);
}

/// A tendency that itself names another state's derivative — the shipped
/// `tests/end_to_end/land_atmosphere_hydrology.esm` shape,
/// `D(lai)/dt ~ sla · D(biomass)/dt`. Substitution recurses, so the chained
/// state integrates against the real rate rather than standing still.
/// `D(b)/dt = 5`, `sla = 2` ⇒ `D(l)/dt = 10`, so `l(3) = 1 + 30`.
#[test]
fn a_chained_tendency_resolves_transitively() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "Chained", "description": "d", "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "b": {"type": "unknown", "units": "kg", "default": 0.0},
                    "l": {"type": "unknown", "units": "m^2", "default": 1.0},
                    "growth": {"type": "parameter", "units": "kg/s", "default": 5.0},
                    "sla": {"type": "parameter", "units": "m^2/kg", "default": 2.0}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["b"], "wrt": "t"}, "rhs": "growth"},
                    {"lhs": {"op": "D", "args": ["l"], "wrt": "t"},
                     "rhs": {"op": "*", "args": ["sla", {"op": "D", "args": ["b"], "wrt": "t"}]}}
                ],
                "tests": [{
                    "id": "chained",
                    "time_span": {"start": 0.0, "end": 3.0},
                    "tolerance": {"rel": 1e-8},
                    "assertions": [
                        {"variable": "b", "time": 3.0, "expected": 15.0},
                        {"variable": "l", "time": 3.0, "expected": 31.0}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    });
    let results = run(&doc);
    assert_eq!(results.len(), 2, "{results:?}");
    assert!(results.iter().all(|r| r.passed), "{results:?}");
}

/// The transform is a FLATTEN-layer rewrite, so the canonical flattened form
/// carries the tendency and every `FlattenedSystem` consumer — both runners,
/// any exporter — agrees by construction rather than by each learning the rule.
#[test]
fn the_flattened_form_carries_the_substituted_tendency() {
    let file = load_string(&own_state_doc().to_string()).expect("document loads");
    let flat = flatten(&file).expect("flattens");
    let dxdt = flat
        .equations
        .iter()
        .find(|eq| matches!(&eq.lhs, earthsci_ast::Expr::Variable(v) if v == "M.dxdt"))
        .expect("the observed equation survives flattening");
    let rendered = format!("{}", dxdt.rhs);
    assert!(
        !rendered.contains("D("),
        "flatten must resolve the RHS derivative, got `{rendered}`"
    );
    assert!(
        rendered.contains("M.k") && rendered.contains("M.x"),
        "the substituted body should be the tendency `-k*x`, got `{rendered}`"
    );
}

/// Scope guard: a SPATIAL `D` (a `wrt` naming an axis) is a rewrite target for
/// a discretization rule (esm-spec §9.6.8), not a tendency. It must survive
/// this phase untouched so the `unlowered_operator` gate still owns it.
#[test]
fn a_spatial_derivative_is_left_for_the_discretization_rule() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "Spatial", "description": "d", "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "u": {"type": "unknown", "units": "K", "default": 1.0},
                    "a": {"type": "parameter", "units": "m/s", "default": 1.0}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["u"], "wrt": "t"},
                     "rhs": {"op": "*", "args": [{"op": "-", "args": ["a"]},
                                                 {"op": "D", "args": ["u"], "wrt": "x"}]}}
                ]
            }
        },
        "domain": {"temporal": {}}
    });
    let file = load_string(&doc.to_string()).expect("document loads");
    let flat = flatten(&file).expect("flattens");
    let rendered = format!("{}", flat.equations[0].rhs);
    assert!(
        rendered.contains("∂M.u/∂x"),
        "the spatial derivative must survive flatten, got `{rendered}`"
    );
    assert!(
        earthsci_ast::extension::flatten::reject_unlowered_operators(&flat).is_err(),
        "and it must still be reported as an unlowered rewrite target"
    );
}

/// CHAIN RULE: `D` of an OBSERVED resolves through the observed's own defining
/// equation (esm-spec §4.2).
///
/// `combo ~ 2*x` carries no `D(combo)/dt`, but its definition does one level
/// down, so `D(combo, t)` is `d/dt(2*x)` = `2*(-k*x)` = `-12` at `t = 0`. This
/// needs no differentiation rule beyond the product rule the resolution already
/// applies to reach a state's tendency, which is why refusing it — what this
/// crate's sibling bindings used to do — was an arbitrary stop one substitution
/// short of the answer.
#[test]
fn d_of_an_observed_resolves_through_its_definition() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "DObsChain",
            "description": "D of an observed, resolved by the chain rule.",
            "authors": ["issue-206"],
            "created": "2026-09-08T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "x": {"type": "unknown", "units": "kg", "default": 2.0},
                    "k": {"type": "parameter", "units": "1/s", "default": 3.0},
                    "combo": {"type": "unknown", "units": "kg"},
                    "dcombo": {"type": "unknown", "units": "kg/s"}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["x"], "wrt": "t"},
                     "rhs": {"op": "*", "args": [{"op": "-", "args": ["k"]}, "x"]}},
                    {"lhs": "combo", "rhs": {"op": "*", "args": [2.0, "x"]}},
                    {"lhs": "dcombo", "rhs": {"op": "D", "args": ["combo"], "wrt": "t"}}
                ],
                "tests": [{
                    "id": "chain",
                    "description": "d(2x)/dt = 2*(-k*x) = -12 at t = 0",
                    "time_span": {"start": 0.0, "end": 1.0},
                    "assertions": [
                        {"variable": "dcombo", "time": 0.0, "expected": -12.0,
                         "tolerance": {"abs": 1e-9}}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    });
    let results = run(&doc);
    assert_eq!(results.len(), 1, "{results:?}");
    assert!(results[0].passed, "{:?}", results[0]);
    assert_eq!(results[0].actual, Some(-12.0));
}

/// A TIME-INVARIANT operand differentiates to a literal `0`, and the folding
/// makes it exactly that rather than a sum of zero terms — so a downstream
/// classifier can still read the equation as constant.
#[test]
fn d_of_a_parameter_is_a_folded_zero() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "DParam", "description": "D of a parameter.",
            "authors": ["issue-206"], "created": "2026-09-08T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "x": {"type": "unknown", "units": "kg", "default": 2.0},
                    "k": {"type": "parameter", "units": "1/s", "default": 3.0},
                    "dk": {"type": "unknown", "units": "1/s^2"}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["x"], "wrt": "t"},
                     "rhs": {"op": "*", "args": [{"op": "-", "args": ["k"]}, "x"]}},
                    {"lhs": "dk", "rhs": {"op": "D", "args": ["k"], "wrt": "t"}}
                ]
            }
        },
        "domain": {"temporal": {}}
    });
    let file = load_string(&doc.to_string()).expect("document loads");
    let flat = flatten(&file).expect("flattens");
    let dk = flat
        .equations
        .iter()
        .find(|eq| matches!(&eq.lhs, earthsci_ast::Expr::Variable(v) if v == "M.dk"))
        .expect("the observed equation survives flattening");
    assert!(
        matches!(&dk.rhs, earthsci_ast::Expr::Number(v) if *v == 0.0),
        "expected a folded literal 0, got `{}`",
        dk.rhs
    );
}

/// A CYCLIC chain must terminate with the node left as authored, and the
/// document must then be REFUSED — never expanded without end, and never given
/// a value.
///
/// This is the case that makes the chain guard load-bearing rather than
/// defensive: an implementation without one does not fail this test, it hangs
/// or overflows its stack. The algebra would give `0` for `k != 1`, which is
/// exactly why the answer has to be a refusal rather than a number — the
/// resolution is a rewrite, not a solver.
#[test]
fn a_cyclic_tendency_terminates_and_is_refused() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "DCycle", "description": "A self-referential tendency.",
            "authors": ["issue-206"], "created": "2026-09-08T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "x": {"type": "unknown", "units": "kg", "default": 2.0},
                    "k": {"type": "parameter", "units": "dimensionless", "default": 0.5}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["x"], "wrt": "t"},
                     "rhs": {"op": "*", "args": ["k", {"op": "D", "args": ["x"], "wrt": "t"}]}}
                ]
            }
        },
        "domain": {"temporal": {}}
    });
    let file = load_string(&doc.to_string()).expect("document loads");
    // Terminates at all — an unguarded substitution never returns.
    let flat = flatten(&file).expect("flattens");
    assert!(
        earthsci_ast::flatten::first_unresolved_rhs_time_derivative(&flat).is_some(),
        "the cyclic `D` must survive as an unresolved rewrite target"
    );
}

/// The motivating shipped document: `tests/validation/mathematical_correctness.esm`
/// exists to check that `d/dt` is LINEAR, and until §4.2 stated the chain rule
/// it could not run at all — Python and Julia refused its left-hand observed and
/// this crate answered `0` for it, so the two sides of the identity disagreed
/// and the property the fixture is named for was untestable. Its only consumer
/// was a round-trip test, which never evaluates anything.
///
/// Both sides must agree AND be non-zero: agreement alone is satisfied by a
/// binding that answers `0` for both.
#[test]
fn the_shipped_linearity_fixture_runs_and_both_sides_agree() {
    let path = common::repo_fixture("validation/mathematical_correctness.esm");
    let text = std::fs::read_to_string(&path).expect("fixture readable");
    let file = load_string(&text).expect("document loads");
    let results = run_inline_tests(&file, Some("LinearityTest"), &opts());
    assert!(!results.is_empty(), "the fixture declares inline tests");
    let get = |name: &str| {
        results
            .iter()
            .find(|r| r.variable == name)
            .unwrap_or_else(|| panic!("no row for {name}"))
    };
    let left = get("derivative_of_combination");
    let right = get("combination_of_derivatives");
    for r in [left, right] {
        assert!(r.passed, "{}: {}", r.variable, r.message);
    }
    let (l, r) = (
        left.actual.expect("left actual"),
        right.actual.expect("right actual"),
    );
    assert!(
        (l - r).abs() <= 1e-12 * l.abs().max(1.0),
        "d(a*u+b*v)/dt = {l} but a*du/dt + b*dv/dt = {r}"
    );
    assert!(
        (l + 0.45).abs() <= 1e-9,
        "expected -0.45 at t = 0, got {l}"
    );
    assert!(
        l.abs() > 1e-6,
        "a binding answering 0 for both sides would satisfy agreement alone"
    );
}
