//! A right-hand-side structural `D(x, t)` resolves to `x`'s TENDENCY
//! (issue #206 item 2).
//!
//! `D` on an equation's left-hand side is what makes the equation
//! differential. On a right-hand side there was no consumer, and all three
//! Rust evaluators answered `D(anything) = 0` "for parity" with one another —
//! so an observed written `dxdt ~ D(x, t)`, the standard shape for asserting a
//! species tendency at `t = 0` (esm-spec §6.6.2, "instantaneous-derivative
//! test shape"), read as exactly `0` and its inline test graded a
//! configuration the model never computed.
//!
//! The value was never the runner's to invent: `x` already carries a defining
//! `D(x)/dt ~ f` equation in the same flattened system. `flatten` phase 5b′
//! (`resolve_rhs_time_derivatives`) substitutes it, upstream of every runner,
//! which is also what lets a model's scoped `D(Chem.A, t)` resolve to a
//! sibling reaction system's mass-action tendency (esm-spec §7.4) without
//! either runner learning anything about reactions.
//!
//! Sabotage check: delete the `resolve_rhs_time_derivatives` call from
//! `flatten_impl` and every numeric test here reports `0` instead.

#![cfg(not(target_arch = "wasm32"))]

use earthsci_ast::{PdeAssertionResult, SolveOptions, flatten, load_string, run_pde_tests};
use serde_json::json;

fn opts() -> SolveOptions {
    SolveOptions {
        reltol: 1e-10,
        abstol: 1e-12,
        ..Default::default()
    }
}

fn run(doc: &serde_json::Value) -> Vec<PdeAssertionResult> {
    let file = load_string(&doc.to_string()).expect("document loads");
    run_pde_tests(&file, None, &opts())
}

/// `D(x)/dt = -k·x` with `k = 3`, `x(0) = 2`, plus an observed `dxdt = D(x, t)`
/// asserted at `t = 0`: the tendency is `-6`, and used to read `0`.
fn own_state_doc() -> serde_json::Value {
    json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "DObsOwn",
            "description": "An observed defined as D(x, t) of this model's own ODE state.",
            "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "x": {"type": "unknown", "units": "kg", "default": 2.0},
                    "k": {"type": "parameter", "units": "1/s", "default": 3.0},
                    "dxdt": {"type": "unknown", "units": "kg/s"}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["x"], "wrt": "t"},
                     "rhs": {"op": "*", "args": [{"op": "-", "args": ["k"]}, "x"]}},
                    {"lhs": "dxdt", "rhs": {"op": "D", "args": ["x"], "wrt": "t"}}
                ],
                "tests": [{
                    "id": "tendency_at_zero",
                    "time_span": {"start": 0.0, "end": 1.0},
                    "assertions": [
                        {"variable": "x", "time": 0.0, "expected": 2.0,
                         "tolerance": {"abs": 1e-12}},
                        {"variable": "dxdt", "time": 0.0, "expected": -6.0,
                         "tolerance": {"abs": 1e-9}}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    })
}

#[test]
fn observed_derivative_of_own_state_is_the_tendency() {
    let results = run(&own_state_doc());
    assert_eq!(results.len(), 2, "{results:?}");
    let dxdt = results
        .iter()
        .find(|r| r.variable == "dxdt")
        .expect("dxdt row");
    assert!(
        dxdt.passed,
        "D(x, t) on a right-hand side must be x's tendency, not 0: {dxdt:?}"
    );
    assert_eq!(dxdt.actual, Some(-6.0), "{dxdt:?}");
}

/// The scoped-reference form the issue reports: a wrapper model observes the
/// tendency of a species owned by a sibling REACTION SYSTEM. The mass-action
/// ODE `D(Chem.A)/dt = -k·A` is generated by flatten (esm-spec §7.4), so the
/// substitution resolves against it with no runner-side knowledge of
/// reactions. `k = 0.5`, `A(0) = 4` ⇒ `dAdt(0) = -2`.
#[test]
fn observed_derivative_of_a_sibling_reaction_systems_species() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "RsScoped",
            "description": "A model observing a sibling reaction system's species tendency.",
            "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "reaction_systems": {
            "Chem": {
                "species": {
                    "A": {"units": "mol/mol", "default": 4.0},
                    "B": {"units": "mol/mol", "default": 0.0}
                },
                "parameters": {"k": {"units": "1/s", "default": 0.5}},
                "reactions": [{
                    "id": "R1",
                    "substrates": [{"species": "A", "stoichiometry": 1}],
                    "products": [{"species": "B", "stoichiometry": 1}],
                    "rate": "k"
                }]
            }
        },
        "models": {
            "Probe": {
                "variables": {
                    "dAdt": {"type": "unknown", "units": "mol/mol/s"}
                },
                "equations": [
                    {"lhs": "dAdt", "rhs": {"op": "D", "args": ["Chem.A"], "wrt": "t"}}
                ],
                "tests": [{
                    "id": "scoped_tendency_at_zero",
                    "time_span": {"start": 0.0, "end": 1.0},
                    "assertions": [
                        {"variable": "dAdt", "time": 0.0, "expected": -2.0,
                         "tolerance": {"abs": 1e-9}}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    });
    let results = run(&doc);
    assert_eq!(results.len(), 1, "{results:?}");
    assert!(results[0].passed, "{:?}", results[0]);
    assert_eq!(results[0].actual, Some(-2.0), "{:?}", results[0]);
}

/// A tendency that itself names another state's derivative — the shipped
/// `tests/end_to_end/land_atmosphere_hydrology.esm` shape,
/// `D(lai)/dt ~ sla · D(biomass)/dt`. Substitution recurses, so the chained
/// state integrates against the real rate rather than standing still.
/// `D(b)/dt = 5`, `sla = 2` ⇒ `D(l)/dt = 10`, so `l(3) = 1 + 30`.
#[test]
fn a_chained_tendency_resolves_transitively() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "Chained", "description": "d", "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "b": {"type": "unknown", "units": "kg", "default": 0.0},
                    "l": {"type": "unknown", "units": "m^2", "default": 1.0},
                    "growth": {"type": "parameter", "units": "kg/s", "default": 5.0},
                    "sla": {"type": "parameter", "units": "m^2/kg", "default": 2.0}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["b"], "wrt": "t"}, "rhs": "growth"},
                    {"lhs": {"op": "D", "args": ["l"], "wrt": "t"},
                     "rhs": {"op": "*", "args": ["sla", {"op": "D", "args": ["b"], "wrt": "t"}]}}
                ],
                "tests": [{
                    "id": "chained",
                    "time_span": {"start": 0.0, "end": 3.0},
                    "tolerance": {"rel": 1e-8},
                    "assertions": [
                        {"variable": "b", "time": 3.0, "expected": 15.0},
                        {"variable": "l", "time": 3.0, "expected": 31.0}
                    ]
                }]
            }
        },
        "domain": {"temporal": {}}
    });
    let results = run(&doc);
    assert_eq!(results.len(), 2, "{results:?}");
    assert!(results.iter().all(|r| r.passed), "{results:?}");
}

/// The transform is a FLATTEN-layer rewrite, so the canonical flattened form
/// carries the tendency and every `FlattenedSystem` consumer — both runners,
/// any exporter — agrees by construction rather than by each learning the rule.
#[test]
fn the_flattened_form_carries_the_substituted_tendency() {
    let file = load_string(&own_state_doc().to_string()).expect("document loads");
    let flat = flatten(&file).expect("flattens");
    let dxdt = flat
        .equations
        .iter()
        .find(|eq| matches!(&eq.lhs, earthsci_ast::Expr::Variable(v) if v == "M.dxdt"))
        .expect("the observed equation survives flattening");
    let rendered = format!("{}", dxdt.rhs);
    assert!(
        !rendered.contains("D("),
        "flatten must resolve the RHS derivative, got `{rendered}`"
    );
    assert!(
        rendered.contains("M.k") && rendered.contains("M.x"),
        "the substituted body should be the tendency `-k*x`, got `{rendered}`"
    );
}

/// Scope guard: a SPATIAL `D` (a `wrt` naming an axis) is a rewrite target for
/// a discretization rule (esm-spec §9.6.8), not a tendency. It must survive
/// this phase untouched so the `unlowered_operator` gate still owns it.
#[test]
fn a_spatial_derivative_is_left_for_the_discretization_rule() {
    let doc = json!({
        "esm": "1.0.0",
        "metadata": {
            "name": "Spatial", "description": "d", "authors": ["issue-206"],
            "created": "2026-09-07T00:00:00Z"
        },
        "models": {
            "M": {
                "variables": {
                    "u": {"type": "unknown", "units": "K", "default": 1.0},
                    "a": {"type": "parameter", "units": "m/s", "default": 1.0}
                },
                "equations": [
                    {"lhs": {"op": "D", "args": ["u"], "wrt": "t"},
                     "rhs": {"op": "*", "args": [{"op": "-", "args": ["a"]},
                                                 {"op": "D", "args": ["u"], "wrt": "x"}]}}
                ]
            }
        },
        "domain": {"temporal": {}}
    });
    let file = load_string(&doc.to_string()).expect("document loads");
    let flat = flatten(&file).expect("flattens");
    let rendered = format!("{}", flat.equations[0].rhs);
    assert!(
        rendered.contains("∂M.u/∂x"),
        "the spatial derivative must survive flatten, got `{rendered}`"
    );
    assert!(
        earthsci_ast::extension::flatten::reject_unlowered_operators(&flat).is_err(),
        "and it must still be reported as an unlowered rewrite target"
    );
}
