# Sub-kernel function tier (ess-cg-subcall-fn, tree_walk/codegen_kernel.jl).
#
# The affine tier compiles one shared `_AccKernel` per template (use site,
# region class) body, but the codegen tier used to INLINE that body at every
# `_NK_SUBCALL` site — un-doing the sharing exactly where compile cost is paid.
# On the duo LMARS momentum RHS the fused emission reached 3.2e6 nodes and a
# ~93-minute / 33 GB first-call compile. The tier under test emits each body
# ONCE as a top-level `@noinline` function and turns every site into a call.
#
# The fixture is generated in the duo rules' EXACT shape, because that shape is
# what mints `_SubCallSite`s: a makearray whose region value applies an
# aggregate-bodied template whose expr holds MORE applies as arithmetic
# OPERANDS. (An apply sitting AT a region-value root — the transport bench
# fixture's shape — fuses into the region variant and never becomes a
# sub-kernel, which is why that fixture cannot exercise this tier.)
#
# This pins:
#   * the tier ENGAGES (`:cg_subcall_fn` fires with the floor at 0) and the
#     kernels still codegen (no decline);
#   * its du is BIT-identical to the pre-tier inline emission
#     (ESS_CG_SUBCALL_FN_DISABLE=1) at Float64 and under ForwardDiff — the
#     emission is value- and order-exact, only wrapped in calls;
#   * the size floor (ESS_CG_SUBCALL_FN_MIN_NODES) keeps small bodies inlined
#     (huge floor ⇒ no functions minted) without changing values;
#   * the compiled RHS stays allocation-free through the call boundary.
# On Julia < 1.12 the tier is unavailable (`_cg_split_supported`; the emitted
# function is the split's inner-`function`-under-RGF mechanism, which boxes
# there) and the pre-tier inlining is the whole path — the differential
# testsets then compare the inline emission to itself, which still must hold.
using Test
using EarthSciAST
using ForwardDiff
using JSON3
include("testutils.jl")
const ESM = EarthSciAST

# A miniature duo-rule-shaped document: D(u)/dt = makearray over the full grid,
# region value = apply(inner), inner = aggregate whose expr combines THREE
# applies of `leaf` (two binding shapes ⇒ two shared sub-kernels, one of them
# called from two sites) inside arithmetic. `leaf` is a plain scalar template
# big enough (~90 nodes emitted) to clear the default stay-inline floor.
function _scf_write_fixture(dir)
    _ix(f, i, j) = Dict("op" => "index", "args" => Any[f, i, j])
    _ap(a, b) = Dict("op" => "apply_expression_template", "args" => Any[],
                     "name" => "leaf", "bindings" => Dict("a" => a, "b" => b))
    leaf_terms = Any[]
    for k in 1:12
        push!(leaf_terms, Dict("op" => "*", "args" => Any[0.5 + 0.01k,
            Dict("op" => "+", "args" => Any[
                Dict("op" => "*", "args" => Any["a", "a"]),
                Dict("op" => "*", "args" => Any["b", 0.3 + 0.02k])])]))
    end
    leaf = Dict("params" => Any["a", "b"],
                "body" => Dict("op" => "+", "args" => leaf_terms))
    inner_expr = Dict("op" => "+", "args" => Any[
        Dict("op" => "*", "args" => Any[0.25, _ap(_ix("f", "i", "j"), _ix("f", "i", "j"))]),
        _ap(_ix("f", "i", "j"), _ix("f", "j", "i")),
        Dict("op" => "*", "args" => Any[
            _ap(_ix("f", "i", "j"), _ix("f", "i", "j")), 0.125])])
    inner = Dict("params" => Any["f"],
                 "body" => Dict("op" => "aggregate", "output_idx" => Any["i", "j"],
                                "args" => Any["f"],
                                "ranges" => Dict("i" => Dict("from" => "x"),
                                                 "j" => Dict("from" => "y")),
                                "expr" => inner_expr))
    rhs = Dict("op" => "makearray", "args" => Any[],
               "regions" => Any[Any[Any[1, "N"], Any[1, "N"]]],
               "values" => Any[Dict("op" => "apply_expression_template",
                                    "args" => Any[], "name" => "inner",
                                    "bindings" => Dict("f" => "u"))])
    doc = Dict(
        "esm" => "1.0.0",
        "metadata" => Dict("name" => "subcall_fn_fixture",
            "description" => "generated by codegen_subcall_fn_test.jl: duo-rule-shaped nested template applies"),
        "metaparameters" => Dict("N" => Dict("type" => "integer", "default" => 5)),
        "index_sets" => Dict("x" => Dict("kind" => "interval", "size" => "N"),
                             "y" => Dict("kind" => "interval", "size" => "N")),
        "models" => Dict("M" => Dict(
            "expression_templates" => Dict("leaf" => leaf, "inner" => inner),
            "variables" => Dict("u" => Dict("type" => "unknown", "units" => "1",
                                            "shape" => Any["x", "y"], "default" => 1.0)),
            "equations" => Any[Dict(
                "lhs" => Dict("op" => "D", "args" => Any["u"], "wrt" => "t"),
                "rhs" => rhs)])))
    path = joinpath(dir, "subcall_fn_fixture.esm")
    open(path, "w") do io
        JSON3.write(io, doc)
    end
    return path
end

# Build the fixture under one env configuration; return the RHS pieces + a
# tally snapshot. The tiers are OPT-IN (see the default notes in
# codegen_kernel.jl / stencil.jl), so every non-reference build here enables
# both the nested boundaries (which mint the `_NK_SUBCALL`s) and the function
# tier; `disable=true` is the bare default path, the differential reference.
function _scf_build(F; disable=false, floor=nothing)
    withenv("ESS_CG_SUBCALL_FN" => (disable ? nothing : "1"),
            "ESS_NESTED_TEMPLATE_BOUNDARY" => (disable ? nothing : "1"),
            "ESS_CG_SUBCALL_FN_MIN_NODES" => (floor === nothing ? nothing : string(floor))) do
        ESM._reset_cascade_tally!()
        flat = ESM.flatten(ESM.load_path(F))
        f!, u0, p, _t, vm = ESM.build_evaluator(flat)
        (f!, u0, p, vm, copy(ESM._CASCADE_TALLY))
    end
end

_scf_du(f!, u, p, t) = (d = similar(u); fill!(d, 0.0); f!(d, u, p, t); d)
_scf_probe(n, k) = Float64[1.1 + 0.8 * sin(0.9i + 1.3k) * cos(0.27i * k) + 0.04i for i in 1:n]
_scf_same(a, b) = size(a) == size(b) && all(a .=== b)
_scf_decl(t) = sum(v for (k, v) in t if startswith(String(k), "codegen_decline"); init=0)

@testset "sub-kernel function tier (ess-cg-subcall-fn)" begin
    mktempdir() do dir
        F = _scf_write_fixture(dir)
        # References must survive load for the tier to have anything to share.
        @test ESM.load_path(F).component_templates !== nothing

        # Reference: the pre-tier emission (every subcall body inlined).
        fr, u0, pr, vmr, rt = _scf_build(F; disable=true)
        @test get(rt, :codegen_kernel, 0) >= 1
        @test get(rt, :cg_subcall_fn, 0) == 0        # tier off ⇒ no functions minted

        # Tier forced onto every body (floor 0): functions are minted, the
        # kernels still codegen, and nothing declines to the interpreter.
        ff, v0, pf, vmf, ft = _scf_build(F; floor=0)
        @test vmr == vmf
        @test u0 == v0
        if ESM._cg_split_supported()
            @test get(ft, :cg_subcall_fn, 0) >= 1    # the tier actually engaged
            @test get(ft, :codegen_kernel, 0) >= 1
            @test _scf_decl(ft) == 0
        else
            @test get(ft, :cg_subcall_fn, 0) == 0    # documented: unavailable < 1.12
        end

        # The tier at its default floor also engages here — `leaf` emits well
        # over the stay-inline floor.
        fd, w0, pd, _vmd, dt = _scf_build(F)
        @test u0 == w0
        ESM._cg_split_supported() && @test get(dt, :cg_subcall_fn, 0) >= 1

        # Huge floor: every body stays inlined — the tier's no-op configuration.
        fi, x0, pi_, _vmi, it = _scf_build(F; floor=typemax(Int) ÷ 2)
        @test get(it, :cg_subcall_fn, 0) == 0
        @test u0 == x0

        # Bit-identical du across all four emissions, Float64 + the AD axis.
        for k in 1:4, t in (0.0, 0.6, 2.75)
            u = k == 1 ? copy(u0) : _scf_probe(length(u0), k)
            df = _scf_du(ff, u, pf, t)
            @test _scf_same(df, _scf_du(fr, u, pr, t))
            @test _scf_same(df, _scf_du(fd, u, pd, t))
            @test _scf_same(df, _scf_du(fi, u, pi_, t))
        end
        Jf = ForwardDiff.jacobian(uu -> _scf_du(ff, uu, pf, 0.4), u0)
        Jr = ForwardDiff.jacobian(uu -> _scf_du(fr, uu, pr, 0.4), u0)
        @test _scf_same(Jf, Jr)

        # The call boundary must not cost allocation: serial path pinned (the
        # threaded tier's fixed dispatch cost is a different property, covered
        # by tree_walk_allocation_test), measured after warmup. A FRESH build
        # inside the pin — the threading verdict caches on a section's first
        # call, so the instances exercised above may already be armed.
        withenv("ESS_THREADS_MIN_CELLS" => string(typemax(Int))) do
            fa, a0, pa, _vma, _at = _scf_build(F; floor=0)
            du = similar(a0)
            f_alloc(f!, du, u, p) = @allocated f!(du, u, p, 0.3)
            fill!(du, 0.0); fa(du, a0, pa, 0.3); fa(du, a0, pa, 0.3)
            @test f_alloc(fa, du, a0, pa) == 0
        end
    end
end
