# Cross-language conformance for `flatten` (esm-libraries-spec §4.7.5 step 4).
#
# Drives the shared corpus at tests/conformance/flatten/cases.json, GENERATED by
# scripts/generate-flatten-corpus.py from the PYTHON oracle. The corpus pins the
# canonical `FlattenedSystem` field set: the ordered contents of every map, the
# per-variable metadata (units, default, shape, update kinds, distribution kind),
# every equation rendered with `to_ascii`, and the derived `system_kind`.
#
# ORDER IS THE POINT. §4.7.5 step 4 makes DOCUMENT ORDER normative — components
# in the order the file declares them, variables in the order their component
# declares them, coupling-merged entries keeping the position of their first
# occurrence — because a parameter vector is positional. Every list below is
# therefore compared IN ORDER, never as a set: Julia's parameter order for
# tests/fixtures/sde/ornstein_uhlenbeck.esm was `[OU.sigma, OU.theta, OU.Bw]` (a
# `Dict` hash order leaking through an `OrderedDict`) where the document declares
# `theta, sigma, Bw`, and a membership-only comparison would have passed.
#
# ── representation differences, normalized here ─────────────────────────────
#
#   * `role` — the oracle tags a flattened variable "state" / "observed" /
#     "parameter" / "species". Julia derives role from BUCKET MEMBERSHIP (the map
#     the variable landed in), which is the same information minus the
#     reaction-species provenance tag, so "species" is compared as "state".
#   * `source_system` — the oracle stores the owning component path on each
#     variable. Julia recovers it from the namespaced key, which is where the
#     name came from: `"A.B.x"` → `"A.B"`.
#   * equation `source_system` — Julia's `Equation` carries no provenance field,
#     so the per-equation owner is not compared. `lhs`, `rhs` and the equation
#     COUNT are, and the count is what §4.7.5 step 4's `field_ics` rule makes
#     comparable across bindings in the first place.
#   * `shape: []` — the oracle records `list(var.shape) if var.shape else None`,
#     so a DECLARED empty shape (a valid scalar shape for a `schedule` / `data` /
#     `remesh` parameter — see `ModelVariable`) is recorded as `null`. Julia keeps
#     the empty vector, so `String[]` is normalized to `nothing` for comparison.
#   * `state_variables[*].shape` of a LIFTED state — the §10.5 pointwise lift
#     promotes the species to the grid shape in Julia (the scoped-ic fold,
#     array-cell discovery and evaluator all need an array state), where the
#     oracle leaves the declared shape and reports the grid only in
#     `lifted_shapes`. `lifted_shapes` itself is compared exactly; a lifted
#     state's `shape` is not.
#   * surviving `apply_expression_template` references — Julia is
#     reference-PRESERVING through flatten (esm-spec §9.6.4 Option B, the
#     documented flatten invariant), the oracle expands at load (Option A). Rule 2
#     says the two images are observably identical, so for a case whose merged
#     `template_registry` is non-empty the equations are compared after
#     `expand_flattened_refs`. That comparison is exact, which is what makes it a
#     real check of the merged registry, its collision renames and its
#     post-scoping dedup rather than a waiver.
#   * `metadata.coupling_rules` — free-text provenance the spec never fixed
#     ("metadata: which components were flattened, which coupling rules applied").
#     The ORDER and the coupling KIND of each entry are pinned; the prose after
#     the kind is not (Julia omits an `operator_compose`'s `translate` map, the
#     oracle prints it).
#   * `domain.independent_variable` — Julia's `Domain` materializes the schema
#     default `"t"` where the oracle preserves the field's absence as `null`.
#     Domain PRESENCE is pinned; a null-vs-`"t"` difference is accepted, a
#     different declared axis is not.
#   * `domain.element_type` / `domain.array_type` — COMPARED normally, no
#     exemption. esm-schema.json defines both (`element_type` ∈ {Float32,
#     Float64}, `array_type` e.g. "CuArray") and they select real behaviour —
#     precision and array backend for the assembled problem — and §4.7.5 step 4
#     says `domain` is the file's section UNCHANGED. Both Julia AND the Python
#     oracle used to drop them at load (each round-tripping the loss back out);
#     both were fixed on 2026-08-24 and the corpus regenerated, so these are
#     ordinary compared fields now. A corpus-INDEPENDENT test still pins the
#     pass-through on tests/valid/model_only.esm, which declares Float32 and is
#     not a corpus fixture.
#
# ── behavioural divergences, NOT normalized ─────────────────────────────────
#
# `_FC_DIVERGENCES` below names every case/field the two bindings genuinely
# disagree on, with the reason. Each entry is a finding to carry back to the
# corpus, not a waiver of Julia's behaviour: the rest of that case is still
# compared in full, and where Julia's answer is the defensible one it is pinned
# LOCALLY here so a regression still fails.

using Test
using JSON3
using EarthSciAST

# `testutils.jl` provides TESTUTILS_REPO_ROOT. `Test` must already be imported
# before it is included (its guard block expands `@test_skip` at lowering time).
if !isdefined(Main, :ESM_TESTUTILS_LOADED)
    include("testutils.jl")
end

const _FLATTEN_CORPUS_PATH =
    joinpath(TESTUTILS_REPO_ROOT, "tests", "conformance", "flatten", "cases.json")
const _FLATTEN_TESTS_DIR = joinpath(TESTUTILS_REPO_ROOT, "tests")

"""
Case ⇒ the corpus fields Julia deliberately does not match, and why.

Every entry is a DIVERGENCE REPORT. Nothing here is "Julia is wrong and we shrug";
each is a place where the two bindings answer differently and the reason is
recorded so the disagreement is visible in the source rather than in a diff.

(RESOLVED 2026-08-24: `independent_variables` used to diverge because the oracle
SORTED them — `for dim in sorted(spatial_dims)` — which §4.7.5 step 4's ordering
rule forbids. It showed only on `full_coupled`, whose `grad` dims are declared
`lon, lat, lev`; every other case's axes happen to sort into document order,
which is why it hid. Julia's document order was the correct one; the ORACLE was
fixed, along with TypeScript, Go and Rust, all four of which accumulated into an
unordered set and sorted on the way out. The corpus now records
`["t","lon","lat","lev"]` and this field is compared normally.)

(RESOLVED 2026-08-24: `equation_count` and `algebraic_variables` on
`full_coupled` used to diverge because the fixture's inert species `OH` had a
reaction tendency in Julia (`D(OH,t) = 0`, the empty stoichiometric sum) and NO
equation at all in the oracle — an unknown nothing names on any LHS, i.e. a
structurally singular DAE. The fixture fix gives `OH` a transport tendency from
`operator_compose`: the `_var` placeholder ranges over A's state variables and
`OH` is one, so BOTH bindings now emit an `OH` equation and both report 4
equations and no algebraic unknowns. Compared normally now.)

(RESOLVED 2026-08-24: `continuous_events` on `full_coupled`. The event's affect
LHS is the `_var` placeholder, and Julia used to namespace it to
`Transport._var` while leaving the `_var` in the same event's CONDITION bare —
one placeholder spelled two ways in one event. `namespace_expr` never touched
the condition because `_var` is in no component's `local_names`; the affect LHS
is a plain NAME rather than an expression, so it took a different path with no
placeholder carve-out. `_collect_model!` now applies the §6.4 rule on both
halves and the field is compared normally.)
* `equations` on `full_coupled` — what survives of the `OH` divergence above is
  the equation's POSITION, and it follows from the two bindings' different
  reaction lowerings rather than from anything about coupling. Julia emits
  `D(OH,t) = 0`, so the transport terms MERGE ONTO that equation and it keeps
  its position among the reaction system's four (§4.7.5 step 4: a merged entry
  keeps the position of its first occurrence) — and the merged RHS still leads
  with the `0 +` term. The oracle has no `OH` reaction equation to merge into,
  so its `OH` equation is Transport's UNMATCHED placeholder clone and sits in
  `models` order, ahead of the reaction system: `[OH, O3, NO, NO2]` against
  Julia's `[O3, NO, NO2, OH]`. Same four equations, same terms. Pinned locally
  below.
* `equations` on `minimal_chemistry` / `metadata_inheritance_coupled` — the
  reaction-lowering coefficient rendering below (`-1 * rate` vs `-rate`), and
  nothing else; the composed advection terms agree exactly. These two are the
  new `operator_compose` tier, so the composition they exist to pin is asserted
  locally below rather than left to the skipped comparison.
* `equations` on `complete_coupling_types` — `EmissionSources` writes
  `D(NO,t) = …` for an `NO` it does not declare and no coupling binds. Julia's
  namespacing only prefixes a component's OWN locals, so the dangling reference
  stays bare; the oracle prefixes it to `EmissionSources.NO`, a name that is in no
  variable map either. The fixture is under-specified and neither answer is
  usable — worth a fixture fix rather than a binding change.
* `state_variables` / `observed_variables` on `edge_enumeration_area_eff` — the
  fixture defines `edge_exists[edge] ~ …` and `edge_dense_id[e] ~ …`, indexed-LHS
  definitions, which esm-spec §6.3.1 makes OBSERVED unknowns ("the variable an
  `index` node indexes is the variable that LHS defines"). Julia puts them in
  `observed_variables`; the oracle puts them in `state_variables` and records
  `observed_variables == []`. The §4.7.5 step-4 table says BOTH — an arrayed
  observed is observed AND materializes into the solved-for vector — so this is
  the one case that could pin that rule and the corpus cannot, because the oracle
  does not implement the observed half. Neither binding implements the table's
  full reading today.
* `equations` on the reaction-lowering cases — a stoichiometric coefficient of
  −1 renders as `-1 * rate` in the oracle and `-rate` (or an infix `a - b`) in
  Julia. Semantically identical, textually different; a `to_ascii`-level
  difference in how the lowering builds the term, not a flatten difference.
* `equations` on `advection_reaction_loaded_ic_bc` — three separate differences,
  none of them about the field set: (i) the oracle NAMESPACES an aggregate's loop
  variables (`Advection.i`) and index-set references, which esm-spec v0.8.0 makes
  wrong — index sets are a document-scoped registry with plain names, and a loop
  variable is body-local, not a component variable; (ii) the oracle prints a range
  as its extent (`1:4`) where Julia prints the index-set name (`lon`); (iii) the
  reaction-lowering coefficient rendering below. A fourth used to sit here —
  `operator_compose` summing the matched RHSs in the opposite order — and is
  RESOLVED (2026-08-24): `Advection` writes `D(Chemistry.O3, t) = …` itself, so
  after namespacing its equations are indistinguishable from the reaction
  system's, and the merge was reading the A/B roles off the dependent variable's
  prefix and getting them backwards. Provenance is now recorded at collection
  (`_attribute_equations!`) and the sum is §4.7.1 step 4's `rhs_A + rhs_B`.
* `equations` on `advanced_coupling` — the ORDER OF COUPLING-ENTRY APPLICATION,
  and only that; all five equations and every term agree. The document's entries
  are, in order, a `couple` (an additive deposition term onto `Chemistry.O3`), a
  `variable_map`, an `operator_compose` (advection). Julia applies them in
  DOCUMENT ORDER, which is how §4.7.5 step 3 reads ("Process each coupling
  entry"), giving `chemistry + deposition + advection`. The oracle buckets the
  entries BY TYPE and runs every `operator_compose` first, then every `couple`,
  then every `variable_map` — a deliberate choice with a stated reason (keeping a
  `variable_map` substitution from renaming a dependent variable out from under
  the merge) — giving `chemistry + advection + deposition`. §4.7.5's own bridge between
  steps 2 and 3 calls the coupling-rule step COMMUTATIVE, which is true of the
  sum and is why nothing but the summand order differs. Nothing in the spec picks one
  evaluation order over the other; Julia's is pinned locally below, and the
  divergence is a finding for the corpus rather than a defect on either side.
* `discrete_events` on `bare_reference_resolution` — the fixture declares
  `daily_reset` on the SUBSYSTEM `SimpleChemistry.Photochemistry`. §4.7.5 step 4
  collects "all events from all component systems", and a subsystem is a
  component system, so Julia emits it with its references namespaced to the
  subsystem path. The oracle's `_namespace_events` walks only the loader's
  hoisted top-level `events` list, which model-level events reach and
  SUBSYSTEM-level ones do not, so the corpus records `[]`. Julia's answer is
  pinned locally below. (`full_coupled`'s model-level `concentration_limit` IS in
  the corpus, which is what localizes this to the subsystem level.)

(RESOLVED 2026-08-24: the whole `advanced_coupling` case, which Julia used to
REFUSE. Its `couple` connector applied a `multiplicative` transform to
`Surface.surface_resistance`, a PARAMETER with no tendency; esm-spec §10.3
defines `multiplicative` against an existing ODE RHS, so Julia raised while the
oracle silently dropped the edge. Julia was right and the ruling is now
normative — `couple_multiplicative_no_tendency`, esm-libraries-spec §4.7.2 — and
the FIXTURE was migrated to the §10.4 spelling the ruling points at: a
`variable_map` whose Expression transform is `<parameter default> * <factor>`,
promoting the parameter to a derived variable. The document flattens cleanly in
both bindings now and every field is compared. The RULING itself no longer has a
corpus case, so it is pinned locally below on a document built here — losing the
refusal must not lose the diagnostic.)
"""
const _FC_DIVERGENCES = Dict{String,Vector{String}}(
    "full_coupled" => ["equations"],
    "complete_coupling_types" => ["equations"],
    "edge_enumeration_area_eff" => ["state_variables", "observed_variables", "equations"],
    "expression_templates_arrhenius" => ["equations"],
    "autocatalytic_reaction" => ["equations"],
    "advection_reaction_loaded_ic_bc" => ["equations"],
    "minimal_chemistry" => ["equations"],
    "metadata_inheritance_coupled" => ["equations"],
    "advanced_coupling" => ["equations"],
    "bare_reference_resolution" => ["discrete_events"],
)

# There is no `_FC_REFUSED_CASES` any more. `advanced_coupling` was its only
# member and the fixture fix made the document flattenable (see above), so every
# corpus case is now compared field by field. A case the oracle itself refuses
# belongs in the corpus's own `refusals` array, which the last testset drives.

_fc_skips(id) = get(_FC_DIVERGENCES, id, String[])
_fc_compare(id, key) = !(key in _fc_skips(id))

# ── recording: the Julia flattened system, in the corpus's language-neutral form ──

"""A default / literal in the corpus's JSON-safe form."""
_fc_scalar(::Nothing) = nothing
_fc_scalar(v::Real) = v
_fc_scalar(v::ASTExpr) = Dict{String,Any}("expr" => to_ascii(v))

"""The ordered `update.kind` tags of a variable, `[]` when it declares none."""
_fc_update_kinds(v::ModelVariable) =
    v.update === nothing ? String[] : String[r.kind for r in v.update]

"""
One flattened variable in the corpus's shape.

`role` is the BUCKET the variable landed in; `source_system` is recovered from
the namespaced key, which is exactly what produced the name; a declared-empty
`shape` is normalized to `nothing` to match the oracle's recording. See the
header for all three.
"""
function _fc_variable(name::AbstractString, v::ModelVariable, role::AbstractString)
    parts = split(String(name), '.')
    Dict{String,Any}(
        "name" => String(name),
        "role" => role,
        "units" => v.units,
        "default" => _fc_scalar(v.default),
        "shape" => (v.shape === nothing || isempty(v.shape)) ? nothing :
                   String[s for s in v.shape],
        "update_kinds" => _fc_update_kinds(v),
        "distribution_kind" => v.distribution === nothing ? nothing : v.distribution.kind,
        "source_system" => length(parts) > 1 ? join(parts[1:end-1], ".") : "",
    )
end

_fc_variable_map(m, role) = [_fc_variable(k, v, role) for (k, v) in m]

_fc_event(ev::ContinuousEvent) = Dict{String,Any}(
    "name" => ev.name,
    "conditions" => String[to_ascii(c) for c in ev.conditions],
    "affects" => String["$(a.lhs) = $(to_ascii(a.rhs))" for a in ev.affects],
)
_fc_event(ev::DiscreteEvent) = Dict{String,Any}(
    "name" => ev.name,
    "conditions" => ev.trigger isa ConditionTrigger ?
        String[to_ascii(ev.trigger.expression)] : String[],
    "affects" => String["$(a.lhs) = $(to_ascii(a.rhs))" for a in ev.affects],
)

"""
The whole §4.7.5 step-4 field set of `flat`, in the corpus's shape.

`equations` is recorded from the EXPANDED image when the merged registry is
non-empty, so Julia's reference-preserving Option-B form compares against the
oracle's Option-A one (esm-spec §9.6.4 rule 2: identical observable behaviour).
"""
function _fc_record(flat)
    eqsrc = isempty(flat.template_registry) ? flat : expand_flattened_refs(flat)
    Dict{String,Any}(
        "system_kind" => system_kind(flat),
        "independent_variables" => String[String(iv) for iv in flat.independent_variables],
        "state_variables" => _fc_variable_map(flat.state_variables, "state"),
        "parameters" => _fc_variable_map(flat.parameters, "parameter"),
        "observed_variables" => _fc_variable_map(flat.observed_variables, "observed"),
        "algebraic_variables" => String[k for k in keys(flat.algebraic_variables)],
        "brownian_parameters" => String[k for k in keys(flat.brownian_parameters)],
        "discrete_parameters" => String[k for k in keys(flat.discrete_parameters)],
        "equation_count" => length(flat.equations),
        "equations" => [Dict{String,Any}("lhs" => to_ascii(eq.lhs),
                                         "rhs" => to_ascii(eq.rhs))
                        for eq in eqsrc.equations],
        "continuous_events" => [_fc_event(e) for e in flat.continuous_events],
        "discrete_events" => [_fc_event(e) for e in flat.discrete_events],
        "domain" => flat.domain === nothing ? nothing :
            Dict{String,Any}("independent_variable" => flat.domain.independent_variable,
                             "element_type" => flat.domain.element_type,
                             "array_type" => flat.domain.array_type),
        "metadata" => Dict{String,Any}(
            "source_systems" => String[s for s in flat.metadata.source_systems],
            "coupling_rules" => String[s for s in flat.metadata.coupling_rules_applied],
            "operator_applies" => String[replace(r, "operator_apply:" => "")
                                         for r in flat.metadata.opaque_coupling_refs
                                         if startswith(r, "operator_apply:")],
            "callbacks" => String[replace(r, "callback:" => "")
                                  for r in flat.metadata.opaque_coupling_refs
                                  if startswith(r, "callback:")],
        ),
        "index_sets" => String[k for k in keys(flat.index_sets)],
        "function_tables" => String[k for k in keys(flat.function_tables)],
        "template_registry" => String[String(k) for k in keys(flat.template_registry)],
        "field_ics" => [Dict{String,Any}("state" => st, "expr" => to_ascii(ex))
                        for (st, ex) in flat.field_ics],
        "loader_fields" => [Dict{String,Any}("name" => lf.name, "owner" => lf.owner,
                                             "source" => lf.subkey,
                                             "file_variable" => lf.var,
                                             "cadence" => lf.cadence)
                            for lf in flat.loader_fields],
        "lifted_shapes" => Dict{String,Any}(k => collect(v)
                                            for (k, v) in flat.lifted_shapes),
        # Not a corpus field: which states the lift promoted, so the comparison
        # can skip exactly those states' `shape` (see the header).
        "_lifted" => Set{String}(keys(flat.lifted_shapes)),
    )
end

# ── comparison helpers ──────────────────────────────────────────────────────

"""A corpus JSON value as plain Julia (`JSON3.Object`/`Array` → Dict/Vector)."""
_fc_plain(v::JSON3.Object) = Dict{String,Any}(String(k) => _fc_plain(x) for (k, x) in pairs(v))
_fc_plain(v::JSON3.Array) = Any[_fc_plain(x) for x in v]
_fc_plain(v) = v

"""Numbers compare by VALUE: the corpus writes `1` where Julia holds `1.0`."""
_fc_eq(a::Real, b::Real) = (a isa Bool || b isa Bool) ? a === b : a == b
_fc_eq(a, b) = isequal(a, b)

"""The oracle's reaction-species tag is Julia's `state` bucket (see the header)."""
_fc_role(r) = r == "species" ? "state" : r

"""The coupling KIND of a metadata rule string — the part before the `(`."""
_fc_rule_kind(s) = first(split(String(s), '('))

"""Compare one variable record field by field, so a failure names the field."""
function _fc_check_variable(id, key, i, exp, act, lifted)
    for f in ("name", "units", "update_kinds", "distribution_kind", "source_system")
        @test (id, key, i, f, act[f]) == (id, key, i, f, exp[f])
    end
    @test (id, key, i, "role", _fc_role(act["role"])) ==
          (id, key, i, "role", _fc_role(exp["role"]))
    @test (id, key, i, "default", _fc_eq(act["default"], exp["default"])) ==
          (id, key, i, "default", true)
    # A lifted state's shape is the post-lift grid in Julia, the declared shape in
    # the oracle; `lifted_shapes` is what pins the grid, and it is compared exactly.
    act["name"] in lifted ||
        @test (id, key, i, "shape", act["shape"]) == (id, key, i, "shape", exp["shape"])
end

function _fc_check_variable_list(id, key, exp, act, lifted)
    # NAMES IN ORDER first: this is the document-order contract, and reporting it
    # as one comparison makes a reordering readable instead of N field failures.
    @test (id, key, [v["name"] for v in act]) ==
          (id, key, [v["name"] for v in exp])
    length(exp) == length(act) || return
    for (i, (e, a)) in enumerate(zip(exp, act))
        _fc_check_variable(id, key, i, e, a, lifted)
    end
end

# ── the corpus ──────────────────────────────────────────────────────────────

@testset "flatten cross-language conformance" begin
    @test isfile(_FLATTEN_CORPUS_PATH)
    corpus = JSON3.read(read(_FLATTEN_CORPUS_PATH, String))
    cases = corpus.cases
    @test !isempty(cases)

    @testset "case: $(case.id)" for case in cases
        id = String(case.id)
        path = joinpath(_FLATTEN_TESTS_DIR, String(case.fixture))
        @test isfile(path)
        isfile(path) || continue

        exp = _fc_plain(case)
        act = _fc_record(flatten(load_path(path)))
        lifted = act["_lifted"]

        @test (id, "system_kind", act["system_kind"]) ==
              (id, "system_kind", exp["system_kind"])
        if _fc_compare(id, "independent_variables")
            @test (id, "independent_variables", act["independent_variables"]) ==
                  (id, "independent_variables", exp["independent_variables"])
        else
            # The oracle sorts; membership is still a real check.
            @test (id, "independent_variables (set)",
                   sort(act["independent_variables"])) ==
                  (id, "independent_variables (set)",
                   sort(String[String(x) for x in exp["independent_variables"]]))
        end

        for key in ("state_variables", "parameters", "observed_variables")
            _fc_compare(id, key) || continue
            _fc_check_variable_list(id, key, exp[key], act[key], lifted)
        end
        for key in ("algebraic_variables", "brownian_parameters", "discrete_parameters",
                    "index_sets", "function_tables", "template_registry")
            _fc_compare(id, key) || continue
            @test (id, key, act[key]) == (id, key, exp[key])
        end

        # §6.3.1: the parameter subsets PARTITION `parameters`; they do not sit
        # beside it. Asserted locally as well as through the corpus, because it is
        # the invariant a "move the wiener parameter out" implementation breaks —
        # and the corpus alone cannot catch a binding that drops both sides.
        params = Set(v["name"] for v in act["parameters"])
        @test (id, "brownian ⊆ parameters",
               issubset(Set(act["brownian_parameters"]), params)) ==
              (id, "brownian ⊆ parameters", true)
        @test (id, "discrete ⊆ parameters",
               issubset(Set(act["discrete_parameters"]), params)) ==
              (id, "discrete ⊆ parameters", true)
        @test (id, "brownian ∩ discrete",
               isempty(intersect(Set(act["brownian_parameters"]),
                                 Set(act["discrete_parameters"])))) ==
              (id, "brownian ∩ discrete", true)
        # `algebraic_variables` is a SUBSET of `state_variables`, not a sibling:
        # a DAE solves for its algebraic unknowns, so they occupy `u` slots.
        unknowns = Set(v["name"] for v in act["state_variables"])
        union!(unknowns, Set(v["name"] for v in act["observed_variables"]))
        @test (id, "algebraic ⊆ unknowns",
               issubset(Set(act["algebraic_variables"]), unknowns)) ==
              (id, "algebraic ⊆ unknowns", true)
        # §6.3.1 row 1: a non-empty brownian bucket IS what makes it an SDE.
        @test (id, "sde iff brownian",
               isempty(act["brownian_parameters"]) || act["system_kind"] == "sde") ==
              (id, "sde iff brownian", true)

        # Equations: the COUNT (which §4.7.5 step 4's `field_ics` removal makes
        # comparable across bindings) and every rendering, in order.
        if _fc_compare(id, "equation_count")
            @test (id, "equation_count", act["equation_count"]) ==
                  (id, "equation_count", exp["equation_count"])
        end
        if _fc_compare(id, "equations") && length(act["equations"]) == length(exp["equations"])
            for (i, (e, a)) in enumerate(zip(exp["equations"], act["equations"]))
                @test (id, "eq", i, "lhs", a["lhs"]) == (id, "eq", i, "lhs", e["lhs"])
                @test (id, "eq", i, "rhs", a["rhs"]) == (id, "eq", i, "rhs", e["rhs"])
            end
        end
        # No `ic` equation may survive in `equations` (§4.7.5 step 4, normative).
        @test (id, "no ic left in equations",
               !any(startswith(e["lhs"], "ic(") for e in act["equations"])) ==
              (id, "no ic left in equations", true)

        for key in ("continuous_events", "discrete_events")
            _fc_compare(id, key) || continue
            @test (id, key, act[key]) == (id, key, exp[key])
        end

        # `field_ics` — the entries removed from `equations`, in order.
        @test (id, "field_ics", act["field_ics"]) == (id, "field_ics", exp["field_ics"])
        @test (id, "loader_fields", act["loader_fields"]) ==
              (id, "loader_fields", exp["loader_fields"])
        # The corpus records `lifted_shapes` sorted by key, so this one map is
        # compared as a sorted association list rather than positionally.
        @test (id, "lifted_shapes", sort!(collect(pairs(act["lifted_shapes"])), by=first)) ==
              (id, "lifted_shapes", sort!(collect(pairs(exp["lifted_shapes"])), by=first))

        # Domain: presence is pinned; Julia's materialized `"t"` default is
        # accepted where the oracle preserved the field's absence (see header).
        @test (id, "domain present", act["domain"] === nothing) ==
              (id, "domain present", exp["domain"] === nothing)
        if act["domain"] !== nothing && exp["domain"] !== nothing
            want = exp["domain"]["independent_variable"]
            @test (id, "domain iv", want === nothing ||
                   want == act["domain"]["independent_variable"]) ==
                  (id, "domain iv", true)
        end

        # Metadata: `source_systems` IS document order and is pinned exactly.
        @test (id, "source_systems", act["metadata"]["source_systems"]) ==
              (id, "source_systems", exp["metadata"]["source_systems"])
        @test (id, "coupling_rule kinds",
               [_fc_rule_kind(r) for r in act["metadata"]["coupling_rules"]]) ==
              (id, "coupling_rule kinds",
               [_fc_rule_kind(r) for r in exp["metadata"]["coupling_rules"]])
        for key in ("operator_applies", "callbacks")
            @test (id, key, act["metadata"][key]) == (id, key, exp["metadata"][key])
        end
    end

    # ── the answers Julia pins locally, where it diverges from the oracle ────
    #
    # `_FC_DIVERGENCES` skips a corpus comparison; it must not leave the field
    # untested, or a regression would land silently. Each expectation below is
    # Julia's own answer with the reason it is the defensible one.
    @testset "document-ordered independent variables" begin
        # tests/valid/full_coupled.esm declares its `grad`/`laplacian` dims in the
        # order lon, lat, lev. §4.7.5 step 4 requires document order; the oracle
        # sorts, so the corpus records [t, lat, lev, lon] and cannot pin this.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid", "full_coupled.esm")))
        @test String[String(iv) for iv in flat.independent_variables] ==
              ["t", "lon", "lat", "lev"]
    end

    @testset "domain element_type / array_type survive flatten" begin
        # HISTORY: the corpus used to record BOTH as null for every case, because
        # the Python oracle's `Domain` dataclass declared neither and dropped them
        # at load (its round trip was lossy too). Julia had the SAME bug and it
        # was fixed here in the same commit. The oracle was fixed on 2026-08-24
        # and the corpus regenerated, so `element_type` / `array_type` are now
        # compared per-case like any other field. §4.7.5 step 4: `domain` is the
        # file's section UNCHANGED.
        #
        # What remains is the corpus-INDEPENDENT half.
        # tests/valid/model_only.esm declares `element_type: "Float32"`. It is not
        # a corpus fixture, so nothing in the per-case comparison would notice
        # Julia dropping it.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid", "model_only.esm")))
        @test flat.domain !== nothing
        @test flat.domain.element_type == "Float32"
        @test flat.domain.array_type === nothing
        # ... and it survives the round trip back out to a document.
        @test EarthSciAST.flattened_to_esm(flat)["domain"]["element_type"] == "Float32"
    end

    @testset "inert reaction species: zero tendency, then transported" begin
        # `AtmosphericChemistry.OH` is declared as a species and touched by no
        # reaction. §4.7.5 step 1's lowering emits `D(species,t) = Σ stoich·rate`
        # for every species; the empty sum is 0. Dropping the equation instead
        # (what the oracle does) makes `OH` an unknown no LHS names — an
        # unconstrained algebraic unknown, i.e. a structurally singular DAE.
        #
        # `OH` is a STATE, so §4.7.1 step 3's placeholder expansion also gives it
        # a transport term, and the merge folds that onto the zero tendency. The
        # `0 +` is therefore the visible trace of the two lowerings differing:
        # the oracle's `OH` equation is transport ALONE and lands in Transport's
        # document position, Julia's is `0 + transport` in the reaction system's.
        # Same four equations either way, which is why `equation_count` and
        # `algebraic_variables` are ordinary compared fields again.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid", "full_coupled.esm")))
        @test haskey(flat.state_variables, "AtmosphericChemistry.OH")
        @test isempty(flat.algebraic_variables)
        eqs = String[to_ascii(eq) for eq in flat.equations]
        @test length(eqs) == 4
        # Position: OH LAST (merged onto the reaction system's fourth equation),
        # where the corpus records it first. This is the whole of what remains
        # of the `equations` divergence on this case.
        @test String[String(split(e, " = ")[1]) for e in eqs] ==
              ["D(AtmosphericChemistry.O3)/Dt", "D(AtmosphericChemistry.NO)/Dt",
               "D(AtmosphericChemistry.NO2)/Dt", "D(AtmosphericChemistry.OH)/Dt"]
        @test eqs[4] == "D(AtmosphericChemistry.OH)/Dt = 0 + " *
              "(-Transport.u) * grad(AtmosphericChemistry.OH) + " *
              "(-Transport.v) * grad(AtmosphericChemistry.OH) + " *
              "(-Transport.w) * grad(AtmosphericChemistry.OH) + " *
              "Transport.K_h * laplacian(AtmosphericChemistry.OH) + " *
              "Transport.K_v * laplacian(AtmosphericChemistry.OH)"
    end

    @testset "operator_compose tier: the composed equations, in full" begin
        # `equations` is skipped for these two cases over the reaction-lowering
        # coefficient rendering alone (`-1 * rate` vs `-rate`). They are the new
        # `operator_compose` tier, so the composition itself — a `_var` template
        # cloned once per state of A and summed onto A's own tendency — is
        # pinned here in full rather than left uncompared.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid",
                                          "minimal_chemistry.esm")))
        chem = "-1.8e-12 * exp(-1370 / SimpleOzone.T) * SimpleOzone.M * " *
               "SimpleOzone.NO * SimpleOzone.O3 + SimpleOzone.jNO2 * SimpleOzone.NO2"
        adv(v) = " + (-Advection.u_wind) * grad(SimpleOzone.$(v))" *
                 " + (-Advection.v_wind) * grad(SimpleOzone.$(v))"
        @test String[to_ascii(eq) for eq in flat.equations] == [
            "D(SimpleOzone.O3)/Dt = " * chem * adv("O3"),
            "D(SimpleOzone.NO)/Dt = " * chem * adv("NO"),
            "D(SimpleOzone.NO2)/Dt = 1.8e-12 * exp(-1370 / SimpleOzone.T) * " *
                "SimpleOzone.M * SimpleOzone.NO * SimpleOzone.O3 - " *
                "SimpleOzone.jNO2 * SimpleOzone.NO2" * adv("NO2"),
        ]

        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid",
                                          "metadata_inheritance_coupled.esm")))
        chem2 = "-1.8e-12 * exp(-1370 / AtmosphericChemistry.T) * " *
                "AtmosphericChemistry.NO * AtmosphericChemistry.O3 + " *
                "AtmosphericChemistry.jNO2 * AtmosphericChemistry.NO2"
        adv2(v) = " + (-AdvectionTransport.u_wind) * grad(AtmosphericChemistry.$(v))" *
                  " + (-AdvectionTransport.v_wind) * grad(AtmosphericChemistry.$(v))"
        @test String[to_ascii(eq) for eq in flat.equations] == [
            "D(AtmosphericChemistry.O3)/Dt = " * chem2 * adv2("O3"),
            "D(AtmosphericChemistry.NO)/Dt = " * chem2 * adv2("NO"),
            "D(AtmosphericChemistry.NO2)/Dt = 1.8e-12 * " *
                "exp(-1370 / AtmosphericChemistry.T) * AtmosphericChemistry.NO * " *
                "AtmosphericChemistry.O3 - AtmosphericChemistry.jNO2 * " *
                "AtmosphericChemistry.NO2" * adv2("NO2"),
        ]
    end

    @testset "operator_compose: a translation match rewrites B's dependent var" begin
        # esm-libraries-spec §4.7.1 step 4, amended 2026-08-24. Nothing in the
        # corpus reaches this: every `translate` map in the shared fixture tree
        # values `"B._var"`, which §10.2 makes REDUNDANT (the case below the
        # next one), so the corpus only ever exercises direct and placeholder
        # matches — for which the rewrite is the identity.
        #
        # `translate: {"A.x": "T.z"}` names two spellings of ONE quantity. The
        # merge consumes `D(T.z)`'s equation, so leaving `T.z` in the summed RHS
        # strands it as an unknown nothing defines. Only the DEPENDENT variable
        # is rewritten: `T.w` is a parameter of B and keeps its name.
        doc = """
        {"esm": "1.0.0",
         "metadata": {"name": "TranslateMatch",
                      "description": "operator_compose across differently-named states",
                      "authors": ["EarthSciAST test suite"],
                      "created": "2026-08-24T00:00:00Z"},
         "models": {
           "A": {"variables": {"x": {"type": "unknown", "units": "mol/mol", "default": 1.0}},
                 "equations": [{"lhs": {"op": "D", "args": ["x"], "wrt": "t"},
                                "rhs": {"op": "-", "args": ["x"]}}]},
           "T": {"variables": {"z": {"type": "unknown", "units": "mol/mol", "default": 1.0},
                               "w": {"type": "parameter", "units": "1/s", "default": 2.0}},
                 "equations": [{"lhs": {"op": "D", "args": ["z"], "wrt": "t"},
                                "rhs": {"op": "*", "args": ["w", "z"]}}]}},
         "coupling": [{"type": "operator_compose", "systems": ["A", "T"],
                       "translate": {"A.x": "T.z"}}]}
        """
        flat = flatten(load_string(doc))
        @test String[to_ascii(eq) for eq in flat.equations] ==
              ["D(A.x)/Dt = -A.x + T.w * A.x"]
        # The rewrite is the point: `T.z` must not survive in the merged RHS.
        @test !occursin("T.z", to_ascii(flat.equations[1]))
    end

    @testset "operator_compose: a `_var` translate value stays harmless" begin
        # esm-spec §10.2's redundancy invariant, and the reason a DIRECT match
        # is tried before a translation match. `tests/scoping/bare_reference_
        # resolution.esm` maps all three chemistry species to `Transport._var`,
        # which asks for exactly what placeholder expansion already does.
        # Consulting the map on the POST-expansion dependent variable made all
        # three collapse onto one equation and left `NO`/`NO2` as unconstrained
        # algebraic unknowns; the corpus records four separate equations.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "scoping",
                                          "bare_reference_resolution.esm")))
        @test length(flat.equations) == 4
        @test isempty(flat.algebraic_variables)
        @test String[String(split(to_ascii(eq), " = ")[1]) for eq in flat.equations] ==
              ["D(SimpleChemistry.O3)/Dt", "D(SimpleChemistry.NO)/Dt",
               "D(SimpleChemistry.NO2)/Dt",
               "D(SimpleChemistry.Photochemistry.NO2_photo)/Dt"]
    end

    @testset "advanced_coupling: coupling entries apply in DOCUMENT order" begin
        # The only difference left on this case (see `_FC_DIVERGENCES`): §4.7.5
        # step 3 says "process each coupling entry", and the document orders them
        # couple → variable_map → operator_compose, so the deposition term lands
        # on `D(Chemistry.O3)` before the advection terms do. The oracle buckets
        # by type and runs every `operator_compose` first. Same five equations,
        # same terms, one summand order apart.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "coupling",
                                          "advanced_coupling.esm")))
        @test String[to_ascii(eq) for eq in flat.equations] == [
            "D(Chemistry.O3)/Dt = -0.1 * Chemistry.O3 * Chemistry.NO + " *
                "(-Surface.deposition_velocity) * Chemistry.O3 + " *
                "(-Transport.wind_speed) * grad(Chemistry.O3) + " *
                "Transport.diffusivity * laplacian(Chemistry.O3)",
            "D(Chemistry.NO)/Dt = -0.1 * Chemistry.O3 * Chemistry.NO + " *
                "(-Transport.wind_speed) * grad(Chemistry.NO) + " *
                "Transport.diffusivity * laplacian(Chemistry.NO)",
            "Chemistry.deposition_flux = Chemistry.O3 * 1.0e-3",
            "Surface.deposition_velocity = 1 / Surface.surface_resistance",
            "Surface.surface_resistance = 100 * (1 + 0.1 * Chemistry.O3)",
        ]
    end

    @testset "subsystem events reach the flattened system" begin
        # §4.7.5 step 4: "all events from all component systems". `daily_reset`
        # is declared on the SUBSYSTEM `SimpleChemistry.Photochemistry`; the
        # oracle only sees hoisted top-level events and records none, so the
        # corpus cannot pin this and `discrete_events` is skipped for the case.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "scoping",
                                          "bare_reference_resolution.esm")))
        @test length(flat.discrete_events) == 1
        ev = flat.discrete_events[1]
        @test ev.name == "daily_reset"
        @test String[a.lhs for a in ev.affects] ==
              ["SimpleChemistry.Photochemistry.photolysis_rate"]
        @test ev.trigger isa EarthSciAST.ConditionTrigger
        @test occursin("SimpleChemistry.Photochemistry.solar_zenith",
                       to_ascii(ev.trigger.expression))
    end

    @testset "operator_compose: the placeholder ranges over STATES only" begin
        # §4.7.1 step 3 expands `_var` over "every state variable in system A".
        # `tests/coupling/advanced_coupling.esm` also declares an OBSERVED
        # unknown, `Chemistry.deposition_flux`, defined algebraically. Expanding
        # over "anything with a defining equation" instead gave it an advection
        # term — a transported diagnostic.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "coupling",
                                          "advanced_coupling.esm")))
        @test any(to_ascii(eq) == "Chemistry.deposition_flux = Chemistry.O3 * 1.0e-3"
                  for eq in flat.equations)
    end

    @testset "couple `multiplicative` onto something with no tendency" begin
        # esm-libraries-spec §4.7.2 / esm-spec §10.3, diagnostic
        # `couple_multiplicative_no_tendency`. `multiplicative` is defined
        # against an EXISTING ODE RHS; a `to` that is a parameter has none, and
        # silently dropping the connector equation is the one outcome a coupling
        # mis-specification must not have — the document declares a coupling and
        # the flattened system carries no trace of it.
        #
        # This used to be pinned by `advanced_coupling`'s refusal. That fixture
        # has been migrated to the §10.4 `variable_map` spelling, so the ruling
        # would otherwise have lost its only test.
        doc = """
        {"esm": "1.0.0",
         "metadata": {"name": "MultiplicativeNoTendency",
                      "description": "multiplicative onto a parameter",
                      "authors": ["EarthSciAST test suite"],
                      "created": "2026-08-24T00:00:00Z"},
         "models": {
           "Chem": {"variables": {"O3": {"type": "unknown", "units": "mol/mol", "default": 1.0}},
                    "equations": [{"lhs": {"op": "D", "args": ["O3"], "wrt": "t"},
                                   "rhs": {"op": "-", "args": ["O3"]}}]},
           "Surface": {"variables": {"r": {"type": "parameter", "units": "mol/mol", "default": 100.0}},
                       "equations": []}},
         "coupling": [{"type": "couple", "systems": ["Chem", "Surface"],
                       "connector": {"equations": [
                         {"from": "Chem.O3", "to": "Surface.r",
                          "transform": "multiplicative",
                          "expression": {"op": "*", "args": [2.0, "Chem.O3"]}}]}}]}
        """
        err = try
            flatten(load_string(doc)); nothing
        catch e
            e
        end
        @test err isa ArgumentError
        @test err === nothing || occursin("Surface.r", sprint(showerror, err))
        @test err === nothing || occursin("no tendency", sprint(showerror, err))
    end

    # ── refusals ────────────────────────────────────────────────────────────
    #
    # The corpus's `error` is the ORACLE's exception class name; Julia spells its
    # own taxonomy differently, so what is asserted is that flatten (or the load
    # that precedes it) REFUSES the document at all — the property the refusal
    # list exists to pin.
    @testset "refusal: $(String(entry.fixture))" for entry in corpus.refusals
        path = joinpath(_FLATTEN_TESTS_DIR, String(entry.fixture))
        @test isfile(path)
        isfile(path) || continue
        @test_throws Exception flatten(load_path(path))
    end
end
