# Cross-language conformance for `flatten` (esm-libraries-spec §4.7.5 step 4).
#
# Drives the shared corpus at tests/conformance/flatten/cases.json, GENERATED by
# scripts/generate-flatten-corpus.py from the PYTHON oracle. The corpus pins the
# canonical `FlattenedSystem` field set: the ordered contents of every map, the
# per-variable metadata (units, default, shape, update kinds, distribution kind),
# every equation rendered with `to_ascii`, and the derived `system_kind`.
#
# ORDER IS THE POINT. §4.7.5 step 4 makes DOCUMENT ORDER normative — components
# in the order the file declares them, variables in the order their component
# declares them, coupling-merged entries keeping the position of their first
# occurrence — because a parameter vector is positional. Every list below is
# therefore compared IN ORDER, never as a set: Julia's parameter order for
# tests/fixtures/sde/ornstein_uhlenbeck.esm was `[OU.sigma, OU.theta, OU.Bw]` (a
# `Dict` hash order leaking through an `OrderedDict`) where the document declares
# `theta, sigma, Bw`, and a membership-only comparison would have passed.
#
# ── representation differences, normalized here ─────────────────────────────
#
#   * `role` — the oracle tags a flattened variable "state" / "observed" /
#     "parameter" / "species". Julia derives role from BUCKET MEMBERSHIP (the map
#     the variable landed in), which is the same information minus the
#     reaction-species provenance tag, so "species" is compared as "state".
#   * `source_system` — the oracle stores the owning component path on each
#     variable. Julia recovers it from the namespaced key, which is where the
#     name came from: `"A.B.x"` → `"A.B"`.
#   * equation `source_system` — Julia's `Equation` carries no provenance field,
#     so the per-equation owner is not compared. `lhs`, `rhs` and the equation
#     COUNT are, and the count is what §4.7.5 step 4's `field_ics` rule makes
#     comparable across bindings in the first place.
#   * `shape: []` — the oracle records `list(var.shape) if var.shape else None`,
#     so a DECLARED empty shape (a valid scalar shape for a `schedule` / `data` /
#     `remesh` parameter — see `ModelVariable`) is recorded as `null`. Julia keeps
#     the empty vector, so `String[]` is normalized to `nothing` for comparison.
#   * `state_variables[*].shape` of a LIFTED state — the §10.5 pointwise lift
#     promotes the species to the grid shape in Julia (the scoped-ic fold,
#     array-cell discovery and evaluator all need an array state), where the
#     oracle leaves the declared shape and reports the grid only in
#     `lifted_shapes`. `lifted_shapes` itself is compared exactly; a lifted
#     state's `shape` is not.
#   * surviving `apply_expression_template` references — Julia is
#     reference-PRESERVING through flatten (esm-spec §9.6.4 Option B, the
#     documented flatten invariant), the oracle expands at load (Option A). Rule 2
#     says the two images are observably identical, so for a case whose merged
#     `template_registry` is non-empty the equations are compared after
#     `expand_flattened_refs`. That comparison is exact, which is what makes it a
#     real check of the merged registry, its collision renames and its
#     post-scoping dedup rather than a waiver.
#   * `metadata.coupling_rules` — free-text provenance the spec never fixed
#     ("metadata: which components were flattened, which coupling rules applied").
#     The ORDER and the coupling KIND of each entry are pinned; the prose after
#     the kind is not (Julia omits an `operator_compose`'s `translate` map, the
#     oracle prints it).
#   * `domain.independent_variable` — Julia's `Domain` materializes the schema
#     default `"t"` where the oracle preserves the field's absence as `null`.
#     Domain PRESENCE is pinned; a null-vs-`"t"` difference is accepted, a
#     different declared axis is not.
#   * `domain.element_type` / `domain.array_type` — an ORACLE GAP, not a
#     contract. The corpus records `null` for both on EVERY case because
#     Python's `Domain` dataclass does not declare them, so the generator's
#     `getattr(flat.domain, "element_type", None)` can only ever record `null`.
#     esm-schema.json defines both (`element_type` ∈ {Float32, Float64},
#     `array_type` e.g. "CuArray") and they select real behaviour — precision and
#     array backend for the assembled problem — and §4.7.5 step 4 says `domain` is
#     the file's section UNCHANGED. Julia now carries them (it dropped them too,
#     until this commit). The gap is pinned as its own test asserting BOTH halves
#     — corpus null everywhere, Julia reading the declared `Float32` — so it fails
#     loudly once the oracle is fixed and the corpus regenerated, instead of the
#     omission being baked into this binding.
#
# ── behavioural divergences, NOT normalized ─────────────────────────────────
#
# `_FC_DIVERGENCES` below names every case/field the two bindings genuinely
# disagree on, with the reason. Each entry is a finding to carry back to the
# corpus, not a waiver of Julia's behaviour: the rest of that case is still
# compared in full, and where Julia's answer is the defensible one it is pinned
# LOCALLY here so a regression still fails.

using Test
using JSON3
using EarthSciAST

# `testutils.jl` provides TESTUTILS_REPO_ROOT. `Test` must already be imported
# before it is included (its guard block expands `@test_skip` at lowering time).
if !isdefined(Main, :ESM_TESTUTILS_LOADED)
    include("testutils.jl")
end

const _FLATTEN_CORPUS_PATH =
    joinpath(TESTUTILS_REPO_ROOT, "tests", "conformance", "flatten", "cases.json")
const _FLATTEN_TESTS_DIR = joinpath(TESTUTILS_REPO_ROOT, "tests")

"""
Case ⇒ the corpus fields Julia deliberately does not match, and why.

Every entry is a DIVERGENCE REPORT. Nothing here is "Julia is wrong and we shrug";
each is a place where the two bindings answer differently and the reason is
recorded so the disagreement is visible in the source rather than in a diff.

* `independent_variables` — the oracle SORTS them (`for dim in
  sorted(spatial_dims)`), which §4.7.5 step 4's ordering rule forbids. It only
  shows on `full_coupled`, whose `grad` dims are declared `lon, lat, lev`; every
  other case's axes happen to sort into document order. Julia's document order is
  pinned locally below.
* `equation_count` / `algebraic_variables` on `full_coupled` — the fixture's
  reaction system declares species `OH` that no reaction touches. §4.7.5 step 1
  says the lowering "still emits `D(species, t) = Σ stoich·rate`", and for `OH`
  that sum is empty, so Julia emits `D(OH,t) = 0` — an inert species is constant.
  The oracle emits no equation at all, which leaves `OH` an unknown that nothing
  names on any LHS, i.e. an ALGEBRAIC unknown with no constraint: a structurally
  singular DAE. Julia's answer is pinned locally below.
* `continuous_events` on `full_coupled` — the event's affect LHS is the `_var`
  placeholder. Julia namespaces it to `Transport._var`, the oracle leaves it bare.
* `equations` on `complete_coupling_types` — `EmissionSources` writes
  `D(NO,t) = …` for an `NO` it does not declare and no coupling binds. Julia's
  namespacing only prefixes a component's OWN locals, so the dangling reference
  stays bare; the oracle prefixes it to `EmissionSources.NO`, a name that is in no
  variable map either. The fixture is under-specified and neither answer is
  usable — worth a fixture fix rather than a binding change.
* `state_variables` / `observed_variables` on `edge_enumeration_area_eff` — the
  fixture defines `edge_exists[edge] ~ …` and `edge_dense_id[e] ~ …`, indexed-LHS
  definitions, which esm-spec §6.3.1 makes OBSERVED unknowns ("the variable an
  `index` node indexes is the variable that LHS defines"). Julia puts them in
  `observed_variables`; the oracle puts them in `state_variables` and records
  `observed_variables == []`. The §4.7.5 step-4 table says BOTH — an arrayed
  observed is observed AND materializes into the solved-for vector — so this is
  the one case that could pin that rule and the corpus cannot, because the oracle
  does not implement the observed half. Neither binding implements the table's
  full reading today.
* `equations` on the reaction-lowering cases — a stoichiometric coefficient of
  −1 renders as `-1 * rate` in the oracle and `-rate` (or an infix `a - b`) in
  Julia. Semantically identical, textually different; a `to_ascii`-level
  difference in how the lowering builds the term, not a flatten difference.
* `equations` on `advection_reaction_loaded_ic_bc` — three separate differences,
  none of them about the field set: (i) the oracle NAMESPACES an aggregate's loop
  variables (`Advection.i`) and index-set references, which esm-spec v0.8.0 makes
  wrong — index sets are a document-scoped registry with plain names, and a loop
  variable is body-local, not a component variable; (ii) the oracle prints a range
  as its extent (`1:4`) where Julia prints the index-set name (`lon`); (iii)
  `operator_compose` sums the matched RHSs in the opposite order.
* the whole `advanced_coupling` case — its `couple` connector applies a
  `multiplicative` transform to `Surface.surface_resistance`, a PARAMETER with no
  tendency. esm-spec §10.3 defines `multiplicative` as "multiply existing tendency
  by expression", so Julia raises a named diagnostic. The oracle silently drops
  the edge (its recorded flattening shows no trace of it, nor of the case's
  `operator_compose` `translate`), which is the one outcome a coupling
  mis-specification must not have. The refusal is asserted below instead.
"""
const _FC_DIVERGENCES = Dict{String,Vector{String}}(
    "full_coupled" => ["independent_variables", "equation_count", "equations",
                       "algebraic_variables", "continuous_events"],
    "complete_coupling_types" => ["equations"],
    "edge_enumeration_area_eff" => ["state_variables", "observed_variables", "equations"],
    "expression_templates_arrhenius" => ["equations"],
    "autocatalytic_reaction" => ["equations"],
    "advection_reaction_loaded_ic_bc" => ["equations"],
)

"""Cases the oracle records but Julia refuses; see `_FC_DIVERGENCES`."""
const _FC_REFUSED_CASES = Set{String}(["advanced_coupling"])

_fc_skips(id) = get(_FC_DIVERGENCES, id, String[])
_fc_compare(id, key) = !(key in _fc_skips(id))

# ── recording: the Julia flattened system, in the corpus's language-neutral form ──

"""A default / literal in the corpus's JSON-safe form."""
_fc_scalar(::Nothing) = nothing
_fc_scalar(v::Real) = v
_fc_scalar(v::ASTExpr) = Dict{String,Any}("expr" => to_ascii(v))

"""The ordered `update.kind` tags of a variable, `[]` when it declares none."""
_fc_update_kinds(v::ModelVariable) =
    v.update === nothing ? String[] : String[r.kind for r in v.update]

"""
One flattened variable in the corpus's shape.

`role` is the BUCKET the variable landed in; `source_system` is recovered from
the namespaced key, which is exactly what produced the name; a declared-empty
`shape` is normalized to `nothing` to match the oracle's recording. See the
header for all three.
"""
function _fc_variable(name::AbstractString, v::ModelVariable, role::AbstractString)
    parts = split(String(name), '.')
    Dict{String,Any}(
        "name" => String(name),
        "role" => role,
        "units" => v.units,
        "default" => _fc_scalar(v.default),
        "shape" => (v.shape === nothing || isempty(v.shape)) ? nothing :
                   String[s for s in v.shape],
        "update_kinds" => _fc_update_kinds(v),
        "distribution_kind" => v.distribution === nothing ? nothing : v.distribution.kind,
        "source_system" => length(parts) > 1 ? join(parts[1:end-1], ".") : "",
    )
end

_fc_variable_map(m, role) = [_fc_variable(k, v, role) for (k, v) in m]

_fc_event(ev::ContinuousEvent) = Dict{String,Any}(
    "name" => ev.name,
    "conditions" => String[to_ascii(c) for c in ev.conditions],
    "affects" => String["$(a.lhs) = $(to_ascii(a.rhs))" for a in ev.affects],
)
_fc_event(ev::DiscreteEvent) = Dict{String,Any}(
    "name" => ev.name,
    "conditions" => ev.trigger isa ConditionTrigger ?
        String[to_ascii(ev.trigger.expression)] : String[],
    "affects" => String["$(a.lhs) = $(to_ascii(a.rhs))" for a in ev.affects],
)

"""
The whole §4.7.5 step-4 field set of `flat`, in the corpus's shape.

`equations` is recorded from the EXPANDED image when the merged registry is
non-empty, so Julia's reference-preserving Option-B form compares against the
oracle's Option-A one (esm-spec §9.6.4 rule 2: identical observable behaviour).
"""
function _fc_record(flat)
    eqsrc = isempty(flat.template_registry) ? flat : expand_flattened_refs(flat)
    Dict{String,Any}(
        "system_kind" => system_kind(flat),
        "independent_variables" => String[String(iv) for iv in flat.independent_variables],
        "state_variables" => _fc_variable_map(flat.state_variables, "state"),
        "parameters" => _fc_variable_map(flat.parameters, "parameter"),
        "observed_variables" => _fc_variable_map(flat.observed_variables, "observed"),
        "algebraic_variables" => String[k for k in keys(flat.algebraic_variables)],
        "brownian_parameters" => String[k for k in keys(flat.brownian_parameters)],
        "discrete_parameters" => String[k for k in keys(flat.discrete_parameters)],
        "equation_count" => length(flat.equations),
        "equations" => [Dict{String,Any}("lhs" => to_ascii(eq.lhs),
                                         "rhs" => to_ascii(eq.rhs))
                        for eq in eqsrc.equations],
        "continuous_events" => [_fc_event(e) for e in flat.continuous_events],
        "discrete_events" => [_fc_event(e) for e in flat.discrete_events],
        "domain" => flat.domain === nothing ? nothing :
            Dict{String,Any}("independent_variable" => flat.domain.independent_variable,
                             "element_type" => flat.domain.element_type,
                             "array_type" => flat.domain.array_type),
        "metadata" => Dict{String,Any}(
            "source_systems" => String[s for s in flat.metadata.source_systems],
            "coupling_rules" => String[s for s in flat.metadata.coupling_rules_applied],
            "operator_applies" => String[replace(r, "operator_apply:" => "")
                                         for r in flat.metadata.opaque_coupling_refs
                                         if startswith(r, "operator_apply:")],
            "callbacks" => String[replace(r, "callback:" => "")
                                  for r in flat.metadata.opaque_coupling_refs
                                  if startswith(r, "callback:")],
        ),
        "index_sets" => String[k for k in keys(flat.index_sets)],
        "function_tables" => String[k for k in keys(flat.function_tables)],
        "template_registry" => String[String(k) for k in keys(flat.template_registry)],
        "field_ics" => [Dict{String,Any}("state" => st, "expr" => to_ascii(ex))
                        for (st, ex) in flat.field_ics],
        "loader_fields" => [Dict{String,Any}("name" => lf.name, "owner" => lf.owner,
                                             "source" => lf.subkey,
                                             "file_variable" => lf.var,
                                             "cadence" => lf.cadence)
                            for lf in flat.loader_fields],
        "lifted_shapes" => Dict{String,Any}(k => collect(v)
                                            for (k, v) in flat.lifted_shapes),
        # Not a corpus field: which states the lift promoted, so the comparison
        # can skip exactly those states' `shape` (see the header).
        "_lifted" => Set{String}(keys(flat.lifted_shapes)),
    )
end

# ── comparison helpers ──────────────────────────────────────────────────────

"""A corpus JSON value as plain Julia (`JSON3.Object`/`Array` → Dict/Vector)."""
_fc_plain(v::JSON3.Object) = Dict{String,Any}(String(k) => _fc_plain(x) for (k, x) in pairs(v))
_fc_plain(v::JSON3.Array) = Any[_fc_plain(x) for x in v]
_fc_plain(v) = v

"""Numbers compare by VALUE: the corpus writes `1` where Julia holds `1.0`."""
_fc_eq(a::Real, b::Real) = (a isa Bool || b isa Bool) ? a === b : a == b
_fc_eq(a, b) = isequal(a, b)

"""The oracle's reaction-species tag is Julia's `state` bucket (see the header)."""
_fc_role(r) = r == "species" ? "state" : r

"""The coupling KIND of a metadata rule string — the part before the `(`."""
_fc_rule_kind(s) = first(split(String(s), '('))

"""Compare one variable record field by field, so a failure names the field."""
function _fc_check_variable(id, key, i, exp, act, lifted)
    for f in ("name", "units", "update_kinds", "distribution_kind", "source_system")
        @test (id, key, i, f, act[f]) == (id, key, i, f, exp[f])
    end
    @test (id, key, i, "role", _fc_role(act["role"])) ==
          (id, key, i, "role", _fc_role(exp["role"]))
    @test (id, key, i, "default", _fc_eq(act["default"], exp["default"])) ==
          (id, key, i, "default", true)
    # A lifted state's shape is the post-lift grid in Julia, the declared shape in
    # the oracle; `lifted_shapes` is what pins the grid, and it is compared exactly.
    act["name"] in lifted ||
        @test (id, key, i, "shape", act["shape"]) == (id, key, i, "shape", exp["shape"])
end

function _fc_check_variable_list(id, key, exp, act, lifted)
    # NAMES IN ORDER first: this is the document-order contract, and reporting it
    # as one comparison makes a reordering readable instead of N field failures.
    @test (id, key, [v["name"] for v in act]) ==
          (id, key, [v["name"] for v in exp])
    length(exp) == length(act) || return
    for (i, (e, a)) in enumerate(zip(exp, act))
        _fc_check_variable(id, key, i, e, a, lifted)
    end
end

# ── the corpus ──────────────────────────────────────────────────────────────

@testset "flatten cross-language conformance" begin
    @test isfile(_FLATTEN_CORPUS_PATH)
    corpus = JSON3.read(read(_FLATTEN_CORPUS_PATH, String))
    cases = corpus.cases
    @test !isempty(cases)

    @testset "case: $(case.id)" for case in cases
        id = String(case.id)
        path = joinpath(_FLATTEN_TESTS_DIR, String(case.fixture))
        @test isfile(path)
        isfile(path) || continue

        if id in _FC_REFUSED_CASES
            # Julia refuses this document; see `_FC_DIVERGENCES`. Assert the
            # refusal rather than the (unreachable) field set, so the divergence
            # is pinned and a silent acceptance would fail here.
            @test_throws ArgumentError flatten(load_path(path))
            continue
        end

        exp = _fc_plain(case)
        act = _fc_record(flatten(load_path(path)))
        lifted = act["_lifted"]

        @test (id, "system_kind", act["system_kind"]) ==
              (id, "system_kind", exp["system_kind"])
        if _fc_compare(id, "independent_variables")
            @test (id, "independent_variables", act["independent_variables"]) ==
                  (id, "independent_variables", exp["independent_variables"])
        else
            # The oracle sorts; membership is still a real check.
            @test (id, "independent_variables (set)",
                   sort(act["independent_variables"])) ==
                  (id, "independent_variables (set)",
                   sort(String[String(x) for x in exp["independent_variables"]]))
        end

        for key in ("state_variables", "parameters", "observed_variables")
            _fc_compare(id, key) || continue
            _fc_check_variable_list(id, key, exp[key], act[key], lifted)
        end
        for key in ("algebraic_variables", "brownian_parameters", "discrete_parameters",
                    "index_sets", "function_tables", "template_registry")
            _fc_compare(id, key) || continue
            @test (id, key, act[key]) == (id, key, exp[key])
        end

        # §6.3.1: the parameter subsets PARTITION `parameters`; they do not sit
        # beside it. Asserted locally as well as through the corpus, because it is
        # the invariant a "move the wiener parameter out" implementation breaks —
        # and the corpus alone cannot catch a binding that drops both sides.
        params = Set(v["name"] for v in act["parameters"])
        @test (id, "brownian ⊆ parameters",
               issubset(Set(act["brownian_parameters"]), params)) ==
              (id, "brownian ⊆ parameters", true)
        @test (id, "discrete ⊆ parameters",
               issubset(Set(act["discrete_parameters"]), params)) ==
              (id, "discrete ⊆ parameters", true)
        @test (id, "brownian ∩ discrete",
               isempty(intersect(Set(act["brownian_parameters"]),
                                 Set(act["discrete_parameters"])))) ==
              (id, "brownian ∩ discrete", true)
        # `algebraic_variables` is a SUBSET of `state_variables`, not a sibling:
        # a DAE solves for its algebraic unknowns, so they occupy `u` slots.
        unknowns = Set(v["name"] for v in act["state_variables"])
        union!(unknowns, Set(v["name"] for v in act["observed_variables"]))
        @test (id, "algebraic ⊆ unknowns",
               issubset(Set(act["algebraic_variables"]), unknowns)) ==
              (id, "algebraic ⊆ unknowns", true)
        # §6.3.1 row 1: a non-empty brownian bucket IS what makes it an SDE.
        @test (id, "sde iff brownian",
               isempty(act["brownian_parameters"]) || act["system_kind"] == "sde") ==
              (id, "sde iff brownian", true)

        # Equations: the COUNT (which §4.7.5 step 4's `field_ics` removal makes
        # comparable across bindings) and every rendering, in order.
        if _fc_compare(id, "equation_count")
            @test (id, "equation_count", act["equation_count"]) ==
                  (id, "equation_count", exp["equation_count"])
        end
        if _fc_compare(id, "equations") && length(act["equations"]) == length(exp["equations"])
            for (i, (e, a)) in enumerate(zip(exp["equations"], act["equations"]))
                @test (id, "eq", i, "lhs", a["lhs"]) == (id, "eq", i, "lhs", e["lhs"])
                @test (id, "eq", i, "rhs", a["rhs"]) == (id, "eq", i, "rhs", e["rhs"])
            end
        end
        # No `ic` equation may survive in `equations` (§4.7.5 step 4, normative).
        @test (id, "no ic left in equations",
               !any(startswith(e["lhs"], "ic(") for e in act["equations"])) ==
              (id, "no ic left in equations", true)

        for key in ("continuous_events", "discrete_events")
            _fc_compare(id, key) || continue
            @test (id, key, act[key]) == (id, key, exp[key])
        end

        # `field_ics` — the entries removed from `equations`, in order.
        @test (id, "field_ics", act["field_ics"]) == (id, "field_ics", exp["field_ics"])
        @test (id, "loader_fields", act["loader_fields"]) ==
              (id, "loader_fields", exp["loader_fields"])
        # The corpus records `lifted_shapes` sorted by key, so this one map is
        # compared as a sorted association list rather than positionally.
        @test (id, "lifted_shapes", sort!(collect(pairs(act["lifted_shapes"])), by=first)) ==
              (id, "lifted_shapes", sort!(collect(pairs(exp["lifted_shapes"])), by=first))

        # Domain: presence is pinned; Julia's materialized `"t"` default is
        # accepted where the oracle preserved the field's absence (see header).
        @test (id, "domain present", act["domain"] === nothing) ==
              (id, "domain present", exp["domain"] === nothing)
        if act["domain"] !== nothing && exp["domain"] !== nothing
            want = exp["domain"]["independent_variable"]
            @test (id, "domain iv", want === nothing ||
                   want == act["domain"]["independent_variable"]) ==
                  (id, "domain iv", true)
        end

        # Metadata: `source_systems` IS document order and is pinned exactly.
        @test (id, "source_systems", act["metadata"]["source_systems"]) ==
              (id, "source_systems", exp["metadata"]["source_systems"])
        @test (id, "coupling_rule kinds",
               [_fc_rule_kind(r) for r in act["metadata"]["coupling_rules"]]) ==
              (id, "coupling_rule kinds",
               [_fc_rule_kind(r) for r in exp["metadata"]["coupling_rules"]])
        for key in ("operator_applies", "callbacks")
            @test (id, key, act["metadata"][key]) == (id, key, exp["metadata"][key])
        end
    end

    # ── the answers Julia pins locally, where it diverges from the oracle ────
    #
    # `_FC_DIVERGENCES` skips a corpus comparison; it must not leave the field
    # untested, or a regression would land silently. Each expectation below is
    # Julia's own answer with the reason it is the defensible one.
    @testset "document-ordered independent variables" begin
        # tests/valid/full_coupled.esm declares its `grad`/`laplacian` dims in the
        # order lon, lat, lev. §4.7.5 step 4 requires document order; the oracle
        # sorts, so the corpus records [t, lat, lev, lon] and cannot pin this.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid", "full_coupled.esm")))
        @test String[String(iv) for iv in flat.independent_variables] ==
              ["t", "lon", "lat", "lev"]
    end

    @testset "domain element_type / array_type: the oracle gap" begin
        # The corpus records BOTH as null for every case, because the Python
        # oracle's `Domain` dataclass declares neither and drops them at load.
        # Assert that — so this test fails the moment the oracle is fixed and the
        # corpus regenerated — AND assert that Julia reads the real declared
        # value, so the omission is not quietly inherited here. §4.7.5 step 4:
        # `domain` is the file's section UNCHANGED.
        corpus = JSON3.read(read(_FLATTEN_CORPUS_PATH, String))
        for case in corpus.cases
            case.domain === nothing && continue
            @test (String(case.id), "corpus element_type",
                   get(case.domain, :element_type, nothing)) ==
                  (String(case.id), "corpus element_type", nothing)
            @test (String(case.id), "corpus array_type",
                   get(case.domain, :array_type, nothing)) ==
                  (String(case.id), "corpus array_type", nothing)
        end
        # tests/valid/model_only.esm declares `element_type: "Float32"`. It is not
        # a corpus fixture, so nothing above would notice Julia dropping it.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid", "model_only.esm")))
        @test flat.domain !== nothing
        @test flat.domain.element_type == "Float32"
        @test flat.domain.array_type === nothing
        # ... and it survives the round trip back out to a document.
        @test EarthSciAST.flattened_to_esm(flat)["domain"]["element_type"] == "Float32"
    end

    @testset "inert reaction species keeps its zero tendency" begin
        # `AtmosphericChemistry.OH` is declared as a species and touched by no
        # reaction. §4.7.5 step 1's lowering emits `D(species,t) = Σ stoich·rate`
        # for every species; the empty sum is 0. Dropping the equation instead
        # (what the oracle does) makes `OH` an unknown no LHS names — an
        # unconstrained algebraic unknown, i.e. a structurally singular DAE.
        flat = flatten(load_path(joinpath(_FLATTEN_TESTS_DIR, "valid", "full_coupled.esm")))
        @test haskey(flat.state_variables, "AtmosphericChemistry.OH")
        @test isempty(flat.algebraic_variables)
        @test any(to_ascii(eq) == "D(AtmosphericChemistry.OH)/Dt = 0"
                  for eq in flat.equations)
    end

    # ── refusals ────────────────────────────────────────────────────────────
    #
    # The corpus's `error` is the ORACLE's exception class name; Julia spells its
    # own taxonomy differently, so what is asserted is that flatten (or the load
    # that precedes it) REFUSES the document at all — the property the refusal
    # list exists to pin.
    @testset "refusal: $(String(entry.fixture))" for entry in corpus.refusals
        path = joinpath(_FLATTEN_TESTS_DIR, String(entry.fixture))
        @test isfile(path)
        isfile(path) || continue
        @test_throws Exception flatten(load_path(path))
    end
end
