# Reduced-rank + contracted region values in the affine stencilizer
# (tree_walk/stencil.jl `_stencilize_indexed` / `_branch_key_indexed!`).
#
# The ESD duo-grid halo-extension rule (`duo_extend`) writes an extended field
# through a makearray whose edge strips are §9.6.8 REDUCED-RANK region values —
# aggregates whose `output_idx` pins the singleton axes with literals
# (`[1, "gi", "gj"]`) — and whose bodies CONTRACT over donor indices with
# constant bounds (the bilinear remap Σ_{k,l} w·q[donor]). The stencilizer used
# to decline both shapes (`makearray reduced-rank region value`,
# `index(aggregate) with contracted index`), throwing the whole fill — and, by
# inlining, its consumers — onto the per-cell tier: on the duo freestream gate
# that meant 7 of 12 sections per-cell, ~3.2M emitted codegen nodes, and a
# 93-minute first-call JIT. The tier under test slices index args to the
# selected region's non-singleton axes (exactly `_resolve_index_of_makearray`'s
# semantics) and unrolls constant-bound contractions into the same
# ⊕-combined term list the per-cell reference builds.
#
# This pins:
#   * ENGAGEMENT: the fixture's fill + consumer both fire affine
#     (`:percell_acc == 0`), and the unroll tally counts;
#   * VALUES: du is BIT-identical to the per-cell scalar reference
#     (`ESS_STENCIL_DISABLE=1`) at Float64 and under ForwardDiff — fold shape,
#     term order, and reducer chaining match `_combine_with_reducer` exactly;
#   * the branch-key walk stays in lockstep (two strips with different donors
#     land in different kernels — wrong keys would fuse them and the value
#     differential above would catch it).
using Test
using EarthSciAST
using ForwardDiff
using JSON3
include("testutils.jl")
const ESM = EarthSciAST

# Miniature duo_extend-shaped fixture. 2 tiles, N×N interior, halo-1 extended
# field qe (N+2 per side):
#   region 0 (base, full rank): clamped copy of the interior;
#   region 1 (tile-1 west strip, REDUCED RANK [1,1,"gj"]): contraction over
#     k ∈ [0,N+1] of a (gj,k)-dependent weight times clamped donor reads from
#     tile 2 — the duo strip shape;
#   region 2 (tile-2 west strip, same [1,1,"gj"] pinned form — the schema
#     requires literal output_idx entries to be exactly 1): different donor
#     (tile 1) and different weight, so the two strips must NOT share a
#     kernel body.
# Consumer: D(q) = 5-point Laplacian-ish combination of qe — affine gathers of
# the materialized extended field.
function _sic_write_fixture(dir)
    _ix(f, args...) = Dict("op" => "index", "args" => Any[f, args...])
    _op(o, args...) = Dict("op" => o, "args" => Any[args...])
    _clamp(e, lo, hi) = _op("max", lo, _op("min", hi, e))
    base = Dict("op" => "aggregate", "output_idx" => Any["gt", "gi", "gj"],
        "args" => Any["q"],
        "ranges" => Dict("gt" => Dict("from" => "tile"),
                         "gi" => Dict("from" => "x_ext"),
                         "gj" => Dict("from" => "y_ext")),
        "expr" => _ix("q", "gt", _clamp(_op("-", "gi", 1), 1, "N"),
                      _clamp(_op("-", "gj", 1), 1, "N")))
    function strip(donor, wshift)
        Dict("op" => "aggregate", "output_idx" => Any[1, 1, "gj"],
            "args" => Any["q"],
            "ranges" => Dict("gj" => Any[2, Dict("op" => "+", "args" => Any["N", 1])],
                             "k" => Any[0, Dict("op" => "+", "args" => Any["N", 1])]),
            "expr" => _op("*",
                _op("/", 1.0,
                    _op("+", 1.0, _op("*", _op("-", "gj", _op("+", "k", wshift)),
                                       _op("-", "gj", _op("+", "k", wshift))))),
                _op("+",
                    _ix("q", donor, _clamp("k", 1, "N"), 1),
                    _op("*", 0.5, _ix("q", donor, _clamp("k", 1, "N"),
                                      _clamp(_op("-", "gj", 1), 1, "N"))))))
    end
    lap = _op("-", _ix("qe", "t", _op("+", "i", 1), _op("+", "j", 1)),
        _op("*", 0.25, _op("+",
            _ix("qe", "t", "i", _op("+", "j", 1)),
            _ix("qe", "t", _op("+", "i", 2), _op("+", "j", 1)),
            _ix("qe", "t", _op("+", "i", 1), "j"),
            _ix("qe", "t", _op("+", "i", 1), _op("+", "j", 2)))))
    doc = Dict(
        "esm" => "1.0.0",
        "metadata" => Dict("name" => "stencil_indexed_contraction_fixture",
            "description" => "generated by stencil_indexed_contraction_test.jl: " *
                "duo_extend-shaped reduced-rank contracted halo fill"),
        "metaparameters" => Dict("N" => Dict("type" => "integer", "default" => 4)),
        "index_sets" => Dict(
            "tile" => Dict("kind" => "interval", "size" => 2),
            "x" => Dict("kind" => "interval", "size" => "N"),
            "y" => Dict("kind" => "interval", "size" => "N"),
            "x_ext" => Dict("kind" => "interval",
                            "size" => Dict("op" => "+", "args" => Any["N", 2])),
            "y_ext" => Dict("kind" => "interval",
                            "size" => Dict("op" => "+", "args" => Any["N", 2]))),
        "models" => Dict("M" => Dict(
            "variables" => Dict(
                "q" => Dict("type" => "unknown", "units" => "1",
                            "shape" => Any["tile", "x", "y"], "default" => 1.0),
                "qe" => Dict("type" => "unknown", "units" => "1",
                             "shape" => Any["tile", "x_ext", "y_ext"])),
            "equations" => Any[
                Dict("lhs" => "qe",
                     "rhs" => Dict("op" => "makearray", "args" => Any[],
                        "regions" => Any[
                            Any[Any[1, 2],
                                Any[1, Dict("op" => "+", "args" => Any["N", 2])],
                                Any[1, Dict("op" => "+", "args" => Any["N", 2])]],
                            Any[Any[1, 1], Any[1, 1],
                                Any[2, Dict("op" => "+", "args" => Any["N", 1])]],
                            Any[Any[2, 2], Any[1, 1],
                                Any[2, Dict("op" => "+", "args" => Any["N", 1])]]],
                        "values" => Any[base, strip(2, 0), strip(1, 1)])),
                Dict("lhs" => Dict("op" => "D", "args" => Any["q"], "wrt" => "t"),
                     "rhs" => Dict("op" => "aggregate",
                        "output_idx" => Any["t", "i", "j"], "args" => Any["qe"],
                        "ranges" => Dict("t" => Dict("from" => "tile"),
                                         "i" => Dict("from" => "x"),
                                         "j" => Dict("from" => "y")),
                        "expr" => lap))])))
    path = joinpath(dir, "stencil_indexed_contraction_fixture.esm")
    open(path, "w") do io
        JSON3.write(io, doc)
    end
    return path
end

function _sic_build(F; disable=false)
    withenv("ESS_STENCIL_DISABLE" => (disable ? "1" : nothing)) do
        ESM._reset_cascade_tally!()
        flat = ESM.flatten(ESM.load_path(F))
        f!, u0, p, _t, vm = ESM.build_evaluator(flat)
        (f!, u0, p, vm, copy(ESM._CASCADE_TALLY))
    end
end

_sic_du(f!, u, p, t) = (d = similar(u); fill!(d, 0.0); f!(d, u, p, t); d)
_sic_probe(n, k) = Float64[1.2 + 0.7 * sin(0.83i + 1.7k) * cos(0.31i * k) + 0.03i for i in 1:n]
_sic_same(a, b) = size(a) == size(b) && all(a .=== b)

@testset "reduced-rank + contracted region values (stencil_indexed)" begin
    mktempdir() do dir
        F = _sic_write_fixture(dir)

        # Default build: everything fires affine, the unroll engages.
        ff, u0, pf, vmf, ft = _sic_build(F)
        @test get(ft, :stencil_indexed_contraction_unroll, 0) >= 1
        @test get(ft, :percell_acc, 0) == 0
        @test get(ft, :affine, 0) >= 1

        # Per-cell scalar reference.
        fr, v0, pr, vmr, rt = _sic_build(F; disable=true)
        @test get(rt, :percell_disabled, 0) >= 1
        @test vmf == vmr
        @test u0 == v0

        # Bitwise-identical du: Float64 probes + the AD axis.
        for k in 1:4, t in (0.0, 0.6, 2.75)
            u = k == 1 ? copy(u0) : _sic_probe(length(u0), k)
            @test _sic_same(_sic_du(ff, u, pf, t), _sic_du(fr, u, pr, t))
        end
        Jf = ForwardDiff.jacobian(uu -> _sic_du(ff, uu, pf, 0.4), u0)
        Jr = ForwardDiff.jacobian(uu -> _sic_du(fr, uu, pr, 0.4), u0)
        @test _sic_same(Jf, Jr)
    end
end
